/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type FileDeleted,
    FileDeletedFromJSON,
    FileDeletedToJSON,
} from '../models/FileDeleted';
import {
    type FileList,
    FileListFromJSON,
    FileListToJSON,
} from '../models/FileList';
import {
    type FileObject,
    FileObjectFromJSON,
    FileObjectToJSON,
} from '../models/FileObject';

export interface DeleteFileRequest {
    id: string;
}

export interface GetFileRequest {
    id: string;
}

export interface GetFileContentRequest {
    id: string;
}

export interface UploadFileRequest {
    file: Blob;
    purpose?: UploadFilePurposeEnum;
}

/**
 * FilesApi - interface
 * 
 * @export
 * @interface FilesApiInterface
 */
export interface FilesApiInterface {
    /**
     * Creates request options for deleteFile without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    deleteFileRequestOpts(requestParameters: DeleteFileRequest): Promise<runtime.RequestOpts>;

    /**
     * Soft-deletes the file row and best-effort removes the underlying R2 object.
     * @summary Delete a file
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDeleted>>;

    /**
     * Soft-deletes the file row and best-effort removes the underlying R2 object.
     * Delete a file
     */
    deleteFile(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDeleted>;

    /**
     * Creates request options for getFile without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getFileRequestOpts(requestParameters: GetFileRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns metadata for a single file.
     * @summary Retrieve a file
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getFileRaw(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>>;

    /**
     * Returns metadata for a single file.
     * Retrieve a file
     */
    getFile(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject>;

    /**
     * Creates request options for getFileContent without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getFileContentRequestOpts(requestParameters: GetFileContentRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the raw bytes with `Content-Type` and `Content-Disposition` headers set from the upload metadata.
     * @summary Download file content
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getFileContentRaw(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Returns the raw bytes with `Content-Type` and `Content-Disposition` headers set from the upload metadata.
     * Download file content
     */
    getFileContent(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for listFiles without sending the request
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    listFilesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns files in reverse-chronological order (newest first).
     * @summary List files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    listFilesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileList>>;

    /**
     * Returns files in reverse-chronological order (newest first).
     * List files
     */
    listFiles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileList>;

    /**
     * Creates request options for uploadFile without sending the request
     * @param {Blob} file The asset bytes (multipart/form-data field)
     * @param {string} [purpose] One of &#x60;vision&#x60;, &#x60;video&#x60;, &#x60;audio&#x60;, or &#x60;document&#x60;. Determines size + mime limits and which models can reference the file. Optional — if omitted, inferred from the file\\\&#39;s MIME type.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    uploadFileRequestOpts(requestParameters: UploadFileRequest): Promise<runtime.RequestOpts>;

    /**
     * Multipart form upload.
     * @summary Upload a file
     * @param {Blob} file The asset bytes (multipart/form-data field)
     * @param {string} [purpose] One of &#x60;vision&#x60;, &#x60;video&#x60;, &#x60;audio&#x60;, or &#x60;document&#x60;. Determines size + mime limits and which models can reference the file. Optional — if omitted, inferred from the file\\\&#39;s MIME type.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    uploadFileRaw(requestParameters: UploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>>;

    /**
     * Multipart form upload.
     * Upload a file
     */
    uploadFile(requestParameters: UploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject>;

}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI implements FilesApiInterface {

    /**
     * Creates request options for deleteFile without sending the request
     */
    async deleteFileRequestOpts(requestParameters: DeleteFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/files/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Soft-deletes the file row and best-effort removes the underlying R2 object.
     * Delete a file
     */
    async deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDeleted>> {
        const requestOptions = await this.deleteFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDeletedFromJSON(jsonValue));
    }

    /**
     * Soft-deletes the file row and best-effort removes the underlying R2 object.
     * Delete a file
     */
    async deleteFile(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDeleted> {
        const response = await this.deleteFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFile without sending the request
     */
    async getFileRequestOpts(requestParameters: GetFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/files/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns metadata for a single file.
     * Retrieve a file
     */
    async getFileRaw(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>> {
        const requestOptions = await this.getFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileObjectFromJSON(jsonValue));
    }

    /**
     * Returns metadata for a single file.
     * Retrieve a file
     */
    async getFile(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject> {
        const response = await this.getFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFileContent without sending the request
     */
    async getFileContentRequestOpts(requestParameters: GetFileContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFileContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/files/{id}/content`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the raw bytes with `Content-Type` and `Content-Disposition` headers set from the upload metadata.
     * Download file content
     */
    async getFileContentRaw(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getFileContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Returns the raw bytes with `Content-Type` and `Content-Disposition` headers set from the upload metadata.
     * Download file content
     */
    async getFileContent(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getFileContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFiles without sending the request
     */
    async listFilesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/files`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns files in reverse-chronological order (newest first).
     * List files
     */
    async listFilesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileList>> {
        const requestOptions = await this.listFilesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileListFromJSON(jsonValue));
    }

    /**
     * Returns files in reverse-chronological order (newest first).
     * List files
     */
    async listFiles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileList> {
        const response = await this.listFilesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadFile without sending the request
     */
    async uploadFileRequestOpts(requestParameters: UploadFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['purpose'] != null) {
            formParams.append('purpose', requestParameters['purpose'] as any);
        }


        let urlPath = `/v1/files`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Multipart form upload.
     * Upload a file
     */
    async uploadFileRaw(requestParameters: UploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileObject>> {
        const requestOptions = await this.uploadFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileObjectFromJSON(jsonValue));
    }

    /**
     * Multipart form upload.
     * Upload a file
     */
    async uploadFile(requestParameters: UploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileObject> {
        const response = await this.uploadFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const UploadFilePurposeEnum = {
    Vision: 'vision',
    Video: 'video',
    Audio: 'audio',
    Document: 'document'
} as const;
export type UploadFilePurposeEnum = typeof UploadFilePurposeEnum[keyof typeof UploadFilePurposeEnum];
