/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateChatCompletionRequest,
    CreateChatCompletionRequestFromJSON,
    CreateChatCompletionRequestToJSON,
} from '../models/CreateChatCompletionRequest';
import {
    type CreateChatCompletionResponse,
    CreateChatCompletionResponseFromJSON,
    CreateChatCompletionResponseToJSON,
} from '../models/CreateChatCompletionResponse';
import {
    type CreateCompletionRequest,
    CreateCompletionRequestFromJSON,
    CreateCompletionRequestToJSON,
} from '../models/CreateCompletionRequest';
import {
    type CreateCompletionResponse,
    CreateCompletionResponseFromJSON,
    CreateCompletionResponseToJSON,
} from '../models/CreateCompletionResponse';
import {
    type CreateResponseRequest,
    CreateResponseRequestFromJSON,
    CreateResponseRequestToJSON,
} from '../models/CreateResponseRequest';
import {
    type CreateResponseResponse,
    CreateResponseResponseFromJSON,
    CreateResponseResponseToJSON,
} from '../models/CreateResponseResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ListModels200Response,
    ListModels200ResponseFromJSON,
    ListModels200ResponseToJSON,
} from '../models/ListModels200Response';

export interface CreateChatCompletionOperationRequest {
    createChatCompletionRequest?: CreateChatCompletionRequest;
}

export interface CreateCompletionOperationRequest {
    createCompletionRequest?: CreateCompletionRequest;
}

export interface CreateResponseOperationRequest {
    createResponseRequest?: CreateResponseRequest;
}

/**
 * OpenaiApi - interface
 * 
 * @export
 * @interface OpenaiApiInterface
 */
export interface OpenaiApiInterface {
    /**
     * Creates request options for createChatCompletion without sending the request
     * @param {CreateChatCompletionRequest} [createChatCompletionRequest] The request body for the chat completion
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createChatCompletionRequestOpts(requestParameters: CreateChatCompletionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a chat completion for the provided messages and parameters.
     * @summary Create a chat completion
     * @param {CreateChatCompletionRequest} [createChatCompletionRequest] The request body for the chat completion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createChatCompletionRaw(requestParameters: CreateChatCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateChatCompletionResponse>>;

    /**
     * Creates a chat completion for the provided messages and parameters.
     * Create a chat completion
     */
    createChatCompletion(requestParameters: CreateChatCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateChatCompletionResponse>;

    /**
     * Creates request options for createCompletion without sending the request
     * @param {CreateCompletionRequest} [createCompletionRequest] The request body for the completion
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createCompletionRequestOpts(requestParameters: CreateCompletionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a completion for the provided prompt and parameters. This is a legacy endpoint — use /v1/chat/completions for new integrations.
     * @summary Create a completion
     * @param {CreateCompletionRequest} [createCompletionRequest] The request body for the completion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createCompletionRaw(requestParameters: CreateCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCompletionResponse>>;

    /**
     * Creates a completion for the provided prompt and parameters. This is a legacy endpoint — use /v1/chat/completions for new integrations.
     * Create a completion
     */
    createCompletion(requestParameters: CreateCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCompletionResponse>;

    /**
     * Creates request options for createResponse without sending the request
     * @param {CreateResponseRequest} [createResponseRequest] The request body for the response.
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createResponseRequestOpts(requestParameters: CreateResponseOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a response for the provided input and parameters.
     * @summary Create a response
     * @param {CreateResponseRequest} [createResponseRequest] The request body for the response.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    createResponseRaw(requestParameters: CreateResponseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponseResponse>>;

    /**
     * Creates a response for the provided input and parameters.
     * Create a response
     */
    createResponse(requestParameters: CreateResponseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponseResponse>;

    /**
     * Creates request options for listModels without sending the request
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    listModelsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Lists all active models with pricing.
     * @summary List models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenaiApiInterface
     */
    listModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModels200Response>>;

    /**
     * Lists all active models with pricing.
     * List models
     */
    listModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModels200Response>;

}

/**
 * 
 */
export class OpenaiApi extends runtime.BaseAPI implements OpenaiApiInterface {

    /**
     * Creates request options for createChatCompletion without sending the request
     */
    async createChatCompletionRequestOpts(requestParameters: CreateChatCompletionOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/chat/completions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChatCompletionRequestToJSON(requestParameters['createChatCompletionRequest']),
        };
    }

    /**
     * Creates a chat completion for the provided messages and parameters.
     * Create a chat completion
     */
    async createChatCompletionRaw(requestParameters: CreateChatCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateChatCompletionResponse>> {
        const requestOptions = await this.createChatCompletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateChatCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Creates a chat completion for the provided messages and parameters.
     * Create a chat completion
     */
    async createChatCompletion(requestParameters: CreateChatCompletionOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateChatCompletionResponse> {
        const response = await this.createChatCompletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCompletion without sending the request
     */
    async createCompletionRequestOpts(requestParameters: CreateCompletionOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/completions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCompletionRequestToJSON(requestParameters['createCompletionRequest']),
        };
    }

    /**
     * Creates a completion for the provided prompt and parameters. This is a legacy endpoint — use /v1/chat/completions for new integrations.
     * Create a completion
     */
    async createCompletionRaw(requestParameters: CreateCompletionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCompletionResponse>> {
        const requestOptions = await this.createCompletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Creates a completion for the provided prompt and parameters. This is a legacy endpoint — use /v1/chat/completions for new integrations.
     * Create a completion
     */
    async createCompletion(requestParameters: CreateCompletionOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCompletionResponse> {
        const response = await this.createCompletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createResponse without sending the request
     */
    async createResponseRequestOpts(requestParameters: CreateResponseOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/responses`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResponseRequestToJSON(requestParameters['createResponseRequest']),
        };
    }

    /**
     * Creates a response for the provided input and parameters.
     * Create a response
     */
    async createResponseRaw(requestParameters: CreateResponseOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponseResponse>> {
        const requestOptions = await this.createResponseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseResponseFromJSON(jsonValue));
    }

    /**
     * Creates a response for the provided input and parameters.
     * Create a response
     */
    async createResponse(requestParameters: CreateResponseOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponseResponse> {
        const response = await this.createResponseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listModels without sending the request
     */
    async listModelsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists all active models with pricing.
     * List models
     */
    async listModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModels200Response>> {
        const requestOptions = await this.listModelsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModels200ResponseFromJSON(jsonValue));
    }

    /**
     * Lists all active models with pricing.
     * List models
     */
    async listModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModels200Response> {
        const response = await this.listModelsRaw(initOverrides);
        return await response.value();
    }

}
