/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CompleteUploadRequest,
    CompleteUploadRequestFromJSON,
    CompleteUploadRequestToJSON,
} from '../models/CompleteUploadRequest';
import {
    type CreateUploadRequest,
    CreateUploadRequestFromJSON,
    CreateUploadRequestToJSON,
} from '../models/CreateUploadRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type UploadObject,
    UploadObjectFromJSON,
    UploadObjectToJSON,
} from '../models/UploadObject';
import {
    type UploadPartObject,
    UploadPartObjectFromJSON,
    UploadPartObjectToJSON,
} from '../models/UploadPartObject';

export interface AddUploadPartRequest {
    id: string;
    data: Blob;
}

export interface CancelUploadRequest {
    id: string;
}

export interface CompleteUploadOperationRequest {
    id: string;
    completeUploadRequest?: CompleteUploadRequest;
}

export interface CreateUploadOperationRequest {
    createUploadRequest?: CreateUploadRequest;
}

/**
 * UploadsApi - interface
 * 
 * @export
 * @interface UploadsApiInterface
 */
export interface UploadsApiInterface {
    /**
     * Creates request options for addUploadPart without sending the request
     * @param {string} id 
     * @param {Blob} data Bytes for this part (multipart/form-data field), max 64 MB
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    addUploadPartRequestOpts(requestParameters: AddUploadPartRequest): Promise<runtime.RequestOpts>;

    /**
     * Uploads up to 64 MB of bytes as one part of a pending session. Parts must be added in order — completing the upload submits them in the order returned to the client.
     * @summary Add a part to an upload
     * @param {string} id 
     * @param {Blob} data Bytes for this part (multipart/form-data field), max 64 MB
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    addUploadPartRaw(requestParameters: AddUploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadPartObject>>;

    /**
     * Uploads up to 64 MB of bytes as one part of a pending session. Parts must be added in order — completing the upload submits them in the order returned to the client.
     * Add a part to an upload
     */
    addUploadPart(requestParameters: AddUploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadPartObject>;

    /**
     * Creates request options for cancelUpload without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    cancelUploadRequestOpts(requestParameters: CancelUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Aborts the underlying R2 multipart upload and marks the session `cancelled`. Idempotent — already-completed or already-cancelled sessions return 404.
     * @summary Cancel an upload
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    cancelUploadRaw(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>>;

    /**
     * Aborts the underlying R2 multipart upload and marks the session `cancelled`. Idempotent — already-completed or already-cancelled sessions return 404.
     * Cancel an upload
     */
    cancelUpload(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject>;

    /**
     * Creates request options for completeUpload without sending the request
     * @param {string} id 
     * @param {CompleteUploadRequest} [completeUploadRequest] Ordered part_ids to assemble
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    completeUploadRequestOpts(requestParameters: CompleteUploadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Assembles the listed parts in order and materializes the upload as a regular `file-...` object referenced via the returned `file` field.
     * @summary Complete an upload
     * @param {string} id 
     * @param {CompleteUploadRequest} [completeUploadRequest] Ordered part_ids to assemble
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    completeUploadRaw(requestParameters: CompleteUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>>;

    /**
     * Assembles the listed parts in order and materializes the upload as a regular `file-...` object referenced via the returned `file` field.
     * Complete an upload
     */
    completeUpload(requestParameters: CompleteUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject>;

    /**
     * Creates request options for createUpload without sending the request
     * @param {CreateUploadRequest} [createUploadRequest] Upload metadata declared up front
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    createUploadRequestOpts(requestParameters: CreateUploadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a chunked upload session for files larger than the single-shot `/v1/files` cap. Sessions expire 1 hour after creation.
     * @summary Create an upload session
     * @param {CreateUploadRequest} [createUploadRequest] Upload metadata declared up front
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    createUploadRaw(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>>;

    /**
     * Creates a chunked upload session for files larger than the single-shot `/v1/files` cap. Sessions expire 1 hour after creation.
     * Create an upload session
     */
    createUpload(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject>;

}

/**
 * 
 */
export class UploadsApi extends runtime.BaseAPI implements UploadsApiInterface {

    /**
     * Creates request options for addUploadPart without sending the request
     */
    async addUploadPartRequestOpts(requestParameters: AddUploadPartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addUploadPart().'
            );
        }

        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling addUploadPart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['data'] != null) {
            formParams.append('data', requestParameters['data'] as any);
        }


        let urlPath = `/v1/uploads/{id}/parts`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Uploads up to 64 MB of bytes as one part of a pending session. Parts must be added in order — completing the upload submits them in the order returned to the client.
     * Add a part to an upload
     */
    async addUploadPartRaw(requestParameters: AddUploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadPartObject>> {
        const requestOptions = await this.addUploadPartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadPartObjectFromJSON(jsonValue));
    }

    /**
     * Uploads up to 64 MB of bytes as one part of a pending session. Parts must be added in order — completing the upload submits them in the order returned to the client.
     * Add a part to an upload
     */
    async addUploadPart(requestParameters: AddUploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadPartObject> {
        const response = await this.addUploadPartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cancelUpload without sending the request
     */
    async cancelUploadRequestOpts(requestParameters: CancelUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Aborts the underlying R2 multipart upload and marks the session `cancelled`. Idempotent — already-completed or already-cancelled sessions return 404.
     * Cancel an upload
     */
    async cancelUploadRaw(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>> {
        const requestOptions = await this.cancelUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadObjectFromJSON(jsonValue));
    }

    /**
     * Aborts the underlying R2 multipart upload and marks the session `cancelled`. Idempotent — already-completed or already-cancelled sessions return 404.
     * Cancel an upload
     */
    async cancelUpload(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject> {
        const response = await this.cancelUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for completeUpload without sending the request
     */
    async completeUploadRequestOpts(requestParameters: CompleteUploadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling completeUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}/complete`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteUploadRequestToJSON(requestParameters['completeUploadRequest']),
        };
    }

    /**
     * Assembles the listed parts in order and materializes the upload as a regular `file-...` object referenced via the returned `file` field.
     * Complete an upload
     */
    async completeUploadRaw(requestParameters: CompleteUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>> {
        const requestOptions = await this.completeUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadObjectFromJSON(jsonValue));
    }

    /**
     * Assembles the listed parts in order and materializes the upload as a regular `file-...` object referenced via the returned `file` field.
     * Complete an upload
     */
    async completeUpload(requestParameters: CompleteUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject> {
        const response = await this.completeUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUpload without sending the request
     */
    async createUploadRequestOpts(requestParameters: CreateUploadOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUploadRequestToJSON(requestParameters['createUploadRequest']),
        };
    }

    /**
     * Creates a chunked upload session for files larger than the single-shot `/v1/files` cap. Sessions expire 1 hour after creation.
     * Create an upload session
     */
    async createUploadRaw(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadObject>> {
        const requestOptions = await this.createUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadObjectFromJSON(jsonValue));
    }

    /**
     * Creates a chunked upload session for files larger than the single-shot `/v1/files` cap. Sessions expire 1 hour after creation.
     * Create an upload session
     */
    async createUpload(requestParameters: CreateUploadOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadObject> {
        const response = await this.createUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
