/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2
     */
    input_audio: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum = {
    InputAudio: 'input_audio'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2TypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('input_audio' in value) || value['input_audio'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2FromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'input_audio': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSON(json['input_audio']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2ToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2ToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'input_audio': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSON(value['input_audio']),
    };
}

