/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File
     */
    file_data?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File
     */
    file_id?: string;
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File {
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'filename': json['filename'] == null ? undefined : json['filename'],
        'file_data': json['file_data'] == null ? undefined : json['file_data'],
        'file_id': json['file_id'] == null ? undefined : json['file_id'],
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'filename': value['filename'],
        'file_data': value['file_data'],
        'file_id': value['file_id'],
    };
}

