/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOfContent } from './ChatCompletionMessageAnyOfContent';
import {
    ChatCompletionMessageAnyOfContentFromJSON,
    ChatCompletionMessageAnyOfContentFromJSONTyped,
    ChatCompletionMessageAnyOfContentToJSON,
    ChatCompletionMessageAnyOfContentToJSONTyped,
} from './ChatCompletionMessageAnyOfContent';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf4
 */
export interface ChatCompletionMessageAnyOf4 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf4RoleEnum}
     * @memberof ChatCompletionMessageAnyOf4
     */
    role: ChatCompletionMessageAnyOf4RoleEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOfContent}
     * @memberof ChatCompletionMessageAnyOf4
     */
    content: ChatCompletionMessageAnyOfContent;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf4
     */
    tool_call_id: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf4RoleEnum = {
    Tool: 'tool'
} as const;
export type ChatCompletionMessageAnyOf4RoleEnum = typeof ChatCompletionMessageAnyOf4RoleEnum[keyof typeof ChatCompletionMessageAnyOf4RoleEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf4 interface.
 */
export function instanceOfChatCompletionMessageAnyOf4(value: object): value is ChatCompletionMessageAnyOf4 {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('tool_call_id' in value) || value['tool_call_id'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf4FromJSON(json: any): ChatCompletionMessageAnyOf4 {
    return ChatCompletionMessageAnyOf4FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionMessageAnyOfContentFromJSON(json['content']),
        'tool_call_id': json['tool_call_id'],
    };
}

export function ChatCompletionMessageAnyOf4ToJSON(json: any): ChatCompletionMessageAnyOf4 {
    return ChatCompletionMessageAnyOf4ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf4ToJSONTyped(value?: ChatCompletionMessageAnyOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionMessageAnyOfContentToJSON(value['content']),
        'tool_call_id': value['tool_call_id'],
    };
}

