/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf3ContentAnyOfInner } from './ChatCompletionMessageAnyOf3ContentAnyOfInner';
import {
    ChatCompletionMessageAnyOf3ContentAnyOfInnerFromJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerFromJSONTyped,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerToJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerToJSONTyped,
} from './ChatCompletionMessageAnyOf3ContentAnyOfInner';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3Content
 */
export interface ChatCompletionMessageAnyOf3Content {
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3Content interface.
 */
export function instanceOfChatCompletionMessageAnyOf3Content(value: object): value is ChatCompletionMessageAnyOf3Content {
    return true;
}

export function ChatCompletionMessageAnyOf3ContentFromJSON(json: any): ChatCompletionMessageAnyOf3Content {
    return ChatCompletionMessageAnyOf3ContentFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3Content {
    return json;
}

export function ChatCompletionMessageAnyOf3ContentToJSON(json: any): ChatCompletionMessageAnyOf3Content {
    return ChatCompletionMessageAnyOf3ContentToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentToJSONTyped(value?: ChatCompletionMessageAnyOf3Content | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

