/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3FromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3FromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3ToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3ToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4ToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4ToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1FromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1FromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1ToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1ToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2 } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2FromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2FromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2ToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2ToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File';
import type { ChatCompletionMessageAnyOfContentAnyOfInner } from './ChatCompletionMessageAnyOfContentAnyOfInner';
import {
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSONTyped,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSONTyped,
} from './ChatCompletionMessageAnyOfContentAnyOfInner';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInner
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInner {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    text: string;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    image_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    video_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    input_audio: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    audio_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInner
     */
    file: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum = {
    Text: 'text',
    ImageUrl: 'image_url',
    VideoUrl: 'video_url',
    InputAudio: 'input_audio',
    AudioUrl: 'audio_url',
    File: 'file'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInner interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInner(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('image_url' in value) || value['image_url'] === undefined) return false;
    if (!('video_url' in value) || value['video_url'] === undefined) return false;
    if (!('input_audio' in value) || value['input_audio'] === undefined) return false;
    if (!('audio_url' in value) || value['audio_url'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInner {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'image_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSON(json['image_url']),
        'video_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON(json['video_url']),
        'input_audio': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSON(json['input_audio']),
        'audio_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON(json['audio_url']),
        'file': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSON(json['file']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInner {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'image_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSON(value['image_url']),
        'video_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON(value['video_url']),
        'input_audio': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSON(value['input_audio']),
        'audio_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON(value['audio_url']),
        'file': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSON(value['file']),
    };
}

