/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3ToolCallsInnerFunction
 */
export interface ChatCompletionMessageAnyOf3ToolCallsInnerFunction {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ToolCallsInnerFunction
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ToolCallsInnerFunction
     */
    arguments: string;
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3ToolCallsInnerFunction interface.
 */
export function instanceOfChatCompletionMessageAnyOf3ToolCallsInnerFunction(value: object): value is ChatCompletionMessageAnyOf3ToolCallsInnerFunction {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('arguments' in value) || value['arguments'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSON(json: any): ChatCompletionMessageAnyOf3ToolCallsInnerFunction {
    return ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3ToolCallsInnerFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'arguments': json['arguments'],
    };
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSON(json: any): ChatCompletionMessageAnyOf3ToolCallsInnerFunction {
    return ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSONTyped(value?: ChatCompletionMessageAnyOf3ToolCallsInnerFunction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'arguments': value['arguments'],
    };
}

