/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf3ToolCallsInnerFunction } from './ChatCompletionMessageAnyOf3ToolCallsInnerFunction';
import {
    ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSONTyped,
    ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSONTyped,
} from './ChatCompletionMessageAnyOf3ToolCallsInnerFunction';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3ToolCallsInner
 */
export interface ChatCompletionMessageAnyOf3ToolCallsInner {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ToolCallsInner
     */
    id: string;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum}
     * @memberof ChatCompletionMessageAnyOf3ToolCallsInner
     */
    type: ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3ToolCallsInnerFunction}
     * @memberof ChatCompletionMessageAnyOf3ToolCallsInner
     */
    _function: ChatCompletionMessageAnyOf3ToolCallsInnerFunction;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum = {
    Function: 'function'
} as const;
export type ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum = typeof ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum[keyof typeof ChatCompletionMessageAnyOf3ToolCallsInnerTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3ToolCallsInner interface.
 */
export function instanceOfChatCompletionMessageAnyOf3ToolCallsInner(value: object): value is ChatCompletionMessageAnyOf3ToolCallsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON(json: any): ChatCompletionMessageAnyOf3ToolCallsInner {
    return ChatCompletionMessageAnyOf3ToolCallsInnerFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3ToolCallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        '_function': ChatCompletionMessageAnyOf3ToolCallsInnerFunctionFromJSON(json['function']),
    };
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerToJSON(json: any): ChatCompletionMessageAnyOf3ToolCallsInner {
    return ChatCompletionMessageAnyOf3ToolCallsInnerToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ToolCallsInnerToJSONTyped(value?: ChatCompletionMessageAnyOf3ToolCallsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'function': ChatCompletionMessageAnyOf3ToolCallsInnerFunctionToJSON(value['_function']),
    };
}

