/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1
     */
    video_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum = {
    VideoUrl: 'video_url'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1TypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('video_url' in value) || value['video_url'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1FromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'video_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON(json['video_url']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1ToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1ToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'video_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON(value['video_url']),
    };
}

