/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl
     */
    url: string;
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

