/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf3 } from './ChatCompletionMessageAnyOf3';
import {
    ChatCompletionMessageAnyOf3FromJSON,
    ChatCompletionMessageAnyOf3FromJSONTyped,
    ChatCompletionMessageAnyOf3ToJSON,
    ChatCompletionMessageAnyOf3ToJSONTyped,
} from './ChatCompletionMessageAnyOf3';
import type { ChatCompletionMessageAnyOf2 } from './ChatCompletionMessageAnyOf2';
import {
    ChatCompletionMessageAnyOf2FromJSON,
    ChatCompletionMessageAnyOf2FromJSONTyped,
    ChatCompletionMessageAnyOf2ToJSON,
    ChatCompletionMessageAnyOf2ToJSONTyped,
} from './ChatCompletionMessageAnyOf2';
import type { ChatCompletionMessageAnyOf1 } from './ChatCompletionMessageAnyOf1';
import {
    ChatCompletionMessageAnyOf1FromJSON,
    ChatCompletionMessageAnyOf1FromJSONTyped,
    ChatCompletionMessageAnyOf1ToJSON,
    ChatCompletionMessageAnyOf1ToJSONTyped,
} from './ChatCompletionMessageAnyOf1';
import type { ChatCompletionMessageAnyOfContent } from './ChatCompletionMessageAnyOfContent';
import {
    ChatCompletionMessageAnyOfContentFromJSON,
    ChatCompletionMessageAnyOfContentFromJSONTyped,
    ChatCompletionMessageAnyOfContentToJSON,
    ChatCompletionMessageAnyOfContentToJSONTyped,
} from './ChatCompletionMessageAnyOfContent';
import type { ChatCompletionMessageAnyOf } from './ChatCompletionMessageAnyOf';
import {
    ChatCompletionMessageAnyOfFromJSON,
    ChatCompletionMessageAnyOfFromJSONTyped,
    ChatCompletionMessageAnyOfToJSON,
    ChatCompletionMessageAnyOfToJSONTyped,
} from './ChatCompletionMessageAnyOf';
import type { ChatCompletionMessageAnyOf3ToolCallsInner } from './ChatCompletionMessageAnyOf3ToolCallsInner';
import {
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSONTyped,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSONTyped,
} from './ChatCompletionMessageAnyOf3ToolCallsInner';
import type { ChatCompletionMessageAnyOf4 } from './ChatCompletionMessageAnyOf4';
import {
    ChatCompletionMessageAnyOf4FromJSON,
    ChatCompletionMessageAnyOf4FromJSONTyped,
    ChatCompletionMessageAnyOf4ToJSON,
    ChatCompletionMessageAnyOf4ToJSONTyped,
} from './ChatCompletionMessageAnyOf4';

/**
 * 
 * @export
 */
export type ChatCompletionMessage =
    | ChatCompletionMessageAnyOf
    | ChatCompletionMessageAnyOf1
    | ChatCompletionMessageAnyOf2
    | ChatCompletionMessageAnyOf3
    | ChatCompletionMessageAnyOf4;


/**
 * Check if a given object implements the ChatCompletionMessage type.
 */
export function instanceOfChatCompletionMessage(value: object): value is ChatCompletionMessage {
    return 'role' in value;
}

export function ChatCompletionMessageFromJSON(json: any): ChatCompletionMessage {
    return ChatCompletionMessageFromJSONTyped(json, false);
}

export function ChatCompletionMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionMessageAnyOfContentFromJSON(json['content']),
        'name': json['name'] == null ? undefined : json['name'],
        'refusal': json['refusal'] == null ? undefined : json['refusal'],
        'tool_calls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON)),
        'tool_call_id': json['tool_call_id'],
    };
}

export function ChatCompletionMessageToJSON(json: any): ChatCompletionMessage {
    return ChatCompletionMessageToJSONTyped(json, false);
}

export function ChatCompletionMessageToJSONTyped(value?: any | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionMessageAnyOfContentToJSON(value['content']),
        'name': value['name'],
        'refusal': value['refusal'],
        'tool_calls': value['tool_calls'] == null ? undefined : ((value['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerToJSON)),
        'tool_call_id': value['tool_call_id'],
    };
}

