/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl
     */
    url: string;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl
     */
    detail?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum = {
    Auto: 'auto',
    Low: 'low',
    High: 'high'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlDetailEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'detail': value['detail'],
    };
}

