/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4
     */
    file: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4File;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum = {
    File: 'file'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4TypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'file': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileFromJSON(json['file']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4ToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4ToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'file': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf4FileToJSON(value['file']),
    };
}

