/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf } from './ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf';
import {
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSONTyped,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSONTyped,
} from './ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf';
import type { ChatCompletionMessageAnyOfContentAnyOfInner } from './ChatCompletionMessageAnyOfContentAnyOfInner';
import {
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSONTyped,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSONTyped,
} from './ChatCompletionMessageAnyOfContentAnyOfInner';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3ContentAnyOfInner
 */
export interface ChatCompletionMessageAnyOf3ContentAnyOfInner {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum}
     * @memberof ChatCompletionMessageAnyOf3ContentAnyOfInner
     */
    type: ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ContentAnyOfInner
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ContentAnyOfInner
     */
    refusal: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum = {
    Text: 'text',
    Refusal: 'refusal'
} as const;
export type ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum = typeof ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum[keyof typeof ChatCompletionMessageAnyOf3ContentAnyOfInnerTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3ContentAnyOfInner interface.
 */
export function instanceOfChatCompletionMessageAnyOf3ContentAnyOfInner(value: object): value is ChatCompletionMessageAnyOf3ContentAnyOfInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerFromJSON(json: any): ChatCompletionMessageAnyOf3ContentAnyOfInner {
    return ChatCompletionMessageAnyOf3ContentAnyOfInnerFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3ContentAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'refusal': json['refusal'],
    };
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerToJSON(json: any): ChatCompletionMessageAnyOf3ContentAnyOfInner {
    return ChatCompletionMessageAnyOf3ContentAnyOfInnerToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerToJSONTyped(value?: ChatCompletionMessageAnyOf3ContentAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'refusal': value['refusal'],
    };
}

