/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOfContent } from './ChatCompletionMessageAnyOfContent';
import {
    ChatCompletionMessageAnyOfContentFromJSON,
    ChatCompletionMessageAnyOfContentFromJSONTyped,
    ChatCompletionMessageAnyOfContentToJSON,
    ChatCompletionMessageAnyOfContentToJSONTyped,
} from './ChatCompletionMessageAnyOfContent';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf
 */
export interface ChatCompletionMessageAnyOf {
    /**
     * 
     * @type {ChatCompletionMessageAnyOfRoleEnum}
     * @memberof ChatCompletionMessageAnyOf
     */
    role: ChatCompletionMessageAnyOfRoleEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOfContent}
     * @memberof ChatCompletionMessageAnyOf
     */
    content: ChatCompletionMessageAnyOfContent;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf
     */
    name?: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOfRoleEnum = {
    Developer: 'developer'
} as const;
export type ChatCompletionMessageAnyOfRoleEnum = typeof ChatCompletionMessageAnyOfRoleEnum[keyof typeof ChatCompletionMessageAnyOfRoleEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf interface.
 */
export function instanceOfChatCompletionMessageAnyOf(value: object): value is ChatCompletionMessageAnyOf {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOfFromJSON(json: any): ChatCompletionMessageAnyOf {
    return ChatCompletionMessageAnyOfFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionMessageAnyOfContentFromJSON(json['content']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ChatCompletionMessageAnyOfToJSON(json: any): ChatCompletionMessageAnyOf {
    return ChatCompletionMessageAnyOfToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfToJSONTyped(value?: ChatCompletionMessageAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionMessageAnyOfContentToJSON(value['content']),
        'name': value['name'],
    };
}

