/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf
     */
    image_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrl;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum = {
    ImageUrl: 'image_url'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('image_url' in value) || value['image_url'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'image_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlFromJSON(json['image_url']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'image_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOfImageUrlToJSON(value['image_url']),
    };
}

