/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOfContentAnyOfInner } from './ChatCompletionMessageAnyOfContentAnyOfInner';
import {
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerFromJSONTyped,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSON,
    ChatCompletionMessageAnyOfContentAnyOfInnerToJSONTyped,
} from './ChatCompletionMessageAnyOfContentAnyOfInner';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOfContent
 */
export interface ChatCompletionMessageAnyOfContent {
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOfContent interface.
 */
export function instanceOfChatCompletionMessageAnyOfContent(value: object): value is ChatCompletionMessageAnyOfContent {
    return true;
}

export function ChatCompletionMessageAnyOfContentFromJSON(json: any): ChatCompletionMessageAnyOfContent {
    return ChatCompletionMessageAnyOfContentFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOfContent {
    return json;
}

export function ChatCompletionMessageAnyOfContentToJSON(json: any): ChatCompletionMessageAnyOfContent {
    return ChatCompletionMessageAnyOfContentToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfContentToJSONTyped(value?: ChatCompletionMessageAnyOfContent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

