/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio
     */
    data: string;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio
     */
    format: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum = {
    Wav: 'wav',
    Mp3: 'mp3'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFormatEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'format': json['format'],
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudioToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf2InputAudio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'format': value['format'],
    };
}

