/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf
 */
export interface ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum}
     * @memberof ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf
     */
    type: ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf
     */
    refusal: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum = {
    Refusal: 'refusal'
} as const;
export type ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum = typeof ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum[keyof typeof ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf interface.
 */
export function instanceOfChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf(value: object): value is ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSON(json: any): ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf {
    return ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'refusal': json['refusal'],
    };
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSON(json: any): ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf {
    return ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSONTyped(value?: ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'refusal': value['refusal'],
    };
}

