/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf3Content } from './ChatCompletionMessageAnyOf3Content';
import {
    ChatCompletionMessageAnyOf3ContentFromJSON,
    ChatCompletionMessageAnyOf3ContentFromJSONTyped,
    ChatCompletionMessageAnyOf3ContentToJSON,
    ChatCompletionMessageAnyOf3ContentToJSONTyped,
} from './ChatCompletionMessageAnyOf3Content';
import type { ChatCompletionMessageAnyOf3ToolCallsInner } from './ChatCompletionMessageAnyOf3ToolCallsInner';
import {
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSONTyped,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSONTyped,
} from './ChatCompletionMessageAnyOf3ToolCallsInner';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf3
 */
export interface ChatCompletionMessageAnyOf3 {
    [key: string]: any | any;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3RoleEnum}
     * @memberof ChatCompletionMessageAnyOf3
     */
    role: ChatCompletionMessageAnyOf3RoleEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf3Content}
     * @memberof ChatCompletionMessageAnyOf3
     */
    content?: ChatCompletionMessageAnyOf3Content | null;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3
     */
    refusal?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf3
     */
    name?: string;
    /**
     * 
     * @type {Array<ChatCompletionMessageAnyOf3ToolCallsInner>}
     * @memberof ChatCompletionMessageAnyOf3
     */
    tool_calls?: Array<ChatCompletionMessageAnyOf3ToolCallsInner>;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf3RoleEnum = {
    Assistant: 'assistant'
} as const;
export type ChatCompletionMessageAnyOf3RoleEnum = typeof ChatCompletionMessageAnyOf3RoleEnum[keyof typeof ChatCompletionMessageAnyOf3RoleEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf3 interface.
 */
export function instanceOfChatCompletionMessageAnyOf3(value: object): value is ChatCompletionMessageAnyOf3 {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf3FromJSON(json: any): ChatCompletionMessageAnyOf3 {
    return ChatCompletionMessageAnyOf3FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf3 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'role': json['role'],
        'content': json['content'] == null ? undefined : ChatCompletionMessageAnyOf3ContentFromJSON(json['content']),
        'refusal': json['refusal'] == null ? undefined : json['refusal'],
        'name': json['name'] == null ? undefined : json['name'],
        'tool_calls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON)),
    };
}

export function ChatCompletionMessageAnyOf3ToJSON(json: any): ChatCompletionMessageAnyOf3 {
    return ChatCompletionMessageAnyOf3ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf3ToJSONTyped(value?: ChatCompletionMessageAnyOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'role': value['role'],
        'content': ChatCompletionMessageAnyOf3ContentToJSON(value['content']),
        'refusal': value['refusal'],
        'name': value['name'],
        'tool_calls': value['tool_calls'] == null ? undefined : ((value['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerToJSON)),
    };
}

