/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl } from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3
 */
export interface ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3
     */
    type: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl}
     * @memberof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3
     */
    audio_url: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrl;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum = {
    AudioUrl: 'audio_url'
} as const;
export type ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum = typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum[keyof typeof ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3TypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 interface.
 */
export function instanceOfChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3(value: object): value is ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('audio_url' in value) || value['audio_url'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3FromJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'audio_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlFromJSON(json['audio_url']),
    };
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3ToJSON(json: any): ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 {
    return ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3ToJSONTyped(value?: ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'audio_url': ChatCompletionMessageAnyOf2ContentAnyOfInnerAnyOf1VideoUrlToJSON(value['audio_url']),
    };
}

