/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOfContentAnyOfInner
 */
export interface ChatCompletionMessageAnyOfContentAnyOfInner {
    /**
     * 
     * @type {ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum}
     * @memberof ChatCompletionMessageAnyOfContentAnyOfInner
     */
    type: ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOfContentAnyOfInner
     */
    text: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum = {
    Text: 'text'
} as const;
export type ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum = typeof ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum[keyof typeof ChatCompletionMessageAnyOfContentAnyOfInnerTypeEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOfContentAnyOfInner interface.
 */
export function instanceOfChatCompletionMessageAnyOfContentAnyOfInner(value: object): value is ChatCompletionMessageAnyOfContentAnyOfInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOfContentAnyOfInnerFromJSON(json: any): ChatCompletionMessageAnyOfContentAnyOfInner {
    return ChatCompletionMessageAnyOfContentAnyOfInnerFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfContentAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOfContentAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
    };
}

export function ChatCompletionMessageAnyOfContentAnyOfInnerToJSON(json: any): ChatCompletionMessageAnyOfContentAnyOfInner {
    return ChatCompletionMessageAnyOfContentAnyOfInnerToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOfContentAnyOfInnerToJSONTyped(value?: ChatCompletionMessageAnyOfContentAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

