/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2Content } from './ChatCompletionMessageAnyOf2Content';
import {
    ChatCompletionMessageAnyOf2ContentFromJSON,
    ChatCompletionMessageAnyOf2ContentFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentToJSON,
    ChatCompletionMessageAnyOf2ContentToJSONTyped,
} from './ChatCompletionMessageAnyOf2Content';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2
 */
export interface ChatCompletionMessageAnyOf2 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2RoleEnum}
     * @memberof ChatCompletionMessageAnyOf2
     */
    role: ChatCompletionMessageAnyOf2RoleEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOf2Content}
     * @memberof ChatCompletionMessageAnyOf2
     */
    content: ChatCompletionMessageAnyOf2Content;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf2
     */
    name?: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf2RoleEnum = {
    User: 'user'
} as const;
export type ChatCompletionMessageAnyOf2RoleEnum = typeof ChatCompletionMessageAnyOf2RoleEnum[keyof typeof ChatCompletionMessageAnyOf2RoleEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2 interface.
 */
export function instanceOfChatCompletionMessageAnyOf2(value: object): value is ChatCompletionMessageAnyOf2 {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf2FromJSON(json: any): ChatCompletionMessageAnyOf2 {
    return ChatCompletionMessageAnyOf2FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionMessageAnyOf2ContentFromJSON(json['content']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ChatCompletionMessageAnyOf2ToJSON(json: any): ChatCompletionMessageAnyOf2 {
    return ChatCompletionMessageAnyOf2ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ToJSONTyped(value?: ChatCompletionMessageAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionMessageAnyOf2ContentToJSON(value['content']),
        'name': value['name'],
    };
}

