/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOf2ContentAnyOfInner } from './ChatCompletionMessageAnyOf2ContentAnyOfInner';
import {
    ChatCompletionMessageAnyOf2ContentAnyOfInnerFromJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerFromJSONTyped,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerToJSON,
    ChatCompletionMessageAnyOf2ContentAnyOfInnerToJSONTyped,
} from './ChatCompletionMessageAnyOf2ContentAnyOfInner';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf2Content
 */
export interface ChatCompletionMessageAnyOf2Content {
}

/**
 * Check if a given object implements the ChatCompletionMessageAnyOf2Content interface.
 */
export function instanceOfChatCompletionMessageAnyOf2Content(value: object): value is ChatCompletionMessageAnyOf2Content {
    return true;
}

export function ChatCompletionMessageAnyOf2ContentFromJSON(json: any): ChatCompletionMessageAnyOf2Content {
    return ChatCompletionMessageAnyOf2ContentFromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf2Content {
    return json;
}

export function ChatCompletionMessageAnyOf2ContentToJSON(json: any): ChatCompletionMessageAnyOf2Content {
    return ChatCompletionMessageAnyOf2ContentToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf2ContentToJSONTyped(value?: ChatCompletionMessageAnyOf2Content | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

