/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionMessageAnyOfContent } from './ChatCompletionMessageAnyOfContent';
import {
    ChatCompletionMessageAnyOfContentFromJSON,
    ChatCompletionMessageAnyOfContentFromJSONTyped,
    ChatCompletionMessageAnyOfContentToJSON,
    ChatCompletionMessageAnyOfContentToJSONTyped,
} from './ChatCompletionMessageAnyOfContent';

/**
 * 
 * @export
 * @interface ChatCompletionMessageAnyOf1
 */
export interface ChatCompletionMessageAnyOf1 {
    /**
     * 
     * @type {ChatCompletionMessageAnyOf1RoleEnum}
     * @memberof ChatCompletionMessageAnyOf1
     */
    role: ChatCompletionMessageAnyOf1RoleEnum;
    /**
     * 
     * @type {ChatCompletionMessageAnyOfContent}
     * @memberof ChatCompletionMessageAnyOf1
     */
    content: ChatCompletionMessageAnyOfContent;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionMessageAnyOf1
     */
    name?: string;
}


/**
 * @export
 */
export const ChatCompletionMessageAnyOf1RoleEnum = {
    System: 'system'
} as const;
export type ChatCompletionMessageAnyOf1RoleEnum = typeof ChatCompletionMessageAnyOf1RoleEnum[keyof typeof ChatCompletionMessageAnyOf1RoleEnum];


/**
 * Check if a given object implements the ChatCompletionMessageAnyOf1 interface.
 */
export function instanceOfChatCompletionMessageAnyOf1(value: object): value is ChatCompletionMessageAnyOf1 {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChatCompletionMessageAnyOf1FromJSON(json: any): ChatCompletionMessageAnyOf1 {
    return ChatCompletionMessageAnyOf1FromJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionMessageAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ChatCompletionMessageAnyOfContentFromJSON(json['content']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ChatCompletionMessageAnyOf1ToJSON(json: any): ChatCompletionMessageAnyOf1 {
    return ChatCompletionMessageAnyOf1ToJSONTyped(json, false);
}

export function ChatCompletionMessageAnyOf1ToJSONTyped(value?: ChatCompletionMessageAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ChatCompletionMessageAnyOfContentToJSON(value['content']),
        'name': value['name'],
    };
}

