/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionUsageCompletionTokensDetails
 */
export interface CompletionUsageCompletionTokensDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsageCompletionTokensDetails
     */
    reasoning_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsageCompletionTokensDetails
     */
    audio_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsageCompletionTokensDetails
     */
    accepted_prediction_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsageCompletionTokensDetails
     */
    rejected_prediction_tokens?: number;
}

/**
 * Check if a given object implements the CompletionUsageCompletionTokensDetails interface.
 */
export function instanceOfCompletionUsageCompletionTokensDetails(value: object): value is CompletionUsageCompletionTokensDetails {
    return true;
}

export function CompletionUsageCompletionTokensDetailsFromJSON(json: any): CompletionUsageCompletionTokensDetails {
    return CompletionUsageCompletionTokensDetailsFromJSONTyped(json, false);
}

export function CompletionUsageCompletionTokensDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionUsageCompletionTokensDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'reasoning_tokens': json['reasoning_tokens'] == null ? undefined : json['reasoning_tokens'],
        'audio_tokens': json['audio_tokens'] == null ? undefined : json['audio_tokens'],
        'accepted_prediction_tokens': json['accepted_prediction_tokens'] == null ? undefined : json['accepted_prediction_tokens'],
        'rejected_prediction_tokens': json['rejected_prediction_tokens'] == null ? undefined : json['rejected_prediction_tokens'],
    };
}

export function CompletionUsageCompletionTokensDetailsToJSON(json: any): CompletionUsageCompletionTokensDetails {
    return CompletionUsageCompletionTokensDetailsToJSONTyped(json, false);
}

export function CompletionUsageCompletionTokensDetailsToJSONTyped(value?: CompletionUsageCompletionTokensDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'reasoning_tokens': value['reasoning_tokens'],
        'audio_tokens': value['audio_tokens'],
        'accepted_prediction_tokens': value['accepted_prediction_tokens'],
        'rejected_prediction_tokens': value['rejected_prediction_tokens'],
    };
}

