/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteUploadRequest
 */
export interface CompleteUploadRequest {
    /**
     * Ordered list of part ids returned by /parts
     * @type {Array<string>}
     * @memberof CompleteUploadRequest
     */
    part_ids: Array<string>;
    /**
     * Optional MD5 of the assembled file
     * @type {string}
     * @memberof CompleteUploadRequest
     */
    md5?: string;
}

/**
 * Check if a given object implements the CompleteUploadRequest interface.
 */
export function instanceOfCompleteUploadRequest(value: object): value is CompleteUploadRequest {
    if (!('part_ids' in value) || value['part_ids'] === undefined) return false;
    return true;
}

export function CompleteUploadRequestFromJSON(json: any): CompleteUploadRequest {
    return CompleteUploadRequestFromJSONTyped(json, false);
}

export function CompleteUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'part_ids': json['part_ids'],
        'md5': json['md5'] == null ? undefined : json['md5'],
    };
}

export function CompleteUploadRequestToJSON(json: any): CompleteUploadRequest {
    return CompleteUploadRequestToJSONTyped(json, false);
}

export function CompleteUploadRequestToJSONTyped(value?: CompleteUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'part_ids': value['part_ids'],
        'md5': value['md5'],
    };
}

