/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompletionUsagePromptTokensDetails } from './CompletionUsagePromptTokensDetails';
import {
    CompletionUsagePromptTokensDetailsFromJSON,
    CompletionUsagePromptTokensDetailsFromJSONTyped,
    CompletionUsagePromptTokensDetailsToJSON,
    CompletionUsagePromptTokensDetailsToJSONTyped,
} from './CompletionUsagePromptTokensDetails';
import type { CompletionUsageCompletionTokensDetails } from './CompletionUsageCompletionTokensDetails';
import {
    CompletionUsageCompletionTokensDetailsFromJSON,
    CompletionUsageCompletionTokensDetailsFromJSONTyped,
    CompletionUsageCompletionTokensDetailsToJSON,
    CompletionUsageCompletionTokensDetailsToJSONTyped,
} from './CompletionUsageCompletionTokensDetails';

/**
 * 
 * @export
 * @interface CompletionUsage
 */
export interface CompletionUsage {
    /**
     * 
     * @type {number}
     * @memberof CompletionUsage
     */
    prompt_tokens: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsage
     */
    completion_tokens: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsage
     */
    total_tokens: number;
    /**
     * 
     * @type {CompletionUsagePromptTokensDetails}
     * @memberof CompletionUsage
     */
    prompt_tokens_details?: CompletionUsagePromptTokensDetails;
    /**
     * 
     * @type {CompletionUsageCompletionTokensDetails}
     * @memberof CompletionUsage
     */
    completion_tokens_details?: CompletionUsageCompletionTokensDetails;
}

/**
 * Check if a given object implements the CompletionUsage interface.
 */
export function instanceOfCompletionUsage(value: object): value is CompletionUsage {
    if (!('prompt_tokens' in value) || value['prompt_tokens'] === undefined) return false;
    if (!('completion_tokens' in value) || value['completion_tokens'] === undefined) return false;
    if (!('total_tokens' in value) || value['total_tokens'] === undefined) return false;
    return true;
}

export function CompletionUsageFromJSON(json: any): CompletionUsage {
    return CompletionUsageFromJSONTyped(json, false);
}

export function CompletionUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt_tokens': json['prompt_tokens'],
        'completion_tokens': json['completion_tokens'],
        'total_tokens': json['total_tokens'],
        'prompt_tokens_details': json['prompt_tokens_details'] == null ? undefined : CompletionUsagePromptTokensDetailsFromJSON(json['prompt_tokens_details']),
        'completion_tokens_details': json['completion_tokens_details'] == null ? undefined : CompletionUsageCompletionTokensDetailsFromJSON(json['completion_tokens_details']),
    };
}

export function CompletionUsageToJSON(json: any): CompletionUsage {
    return CompletionUsageToJSONTyped(json, false);
}

export function CompletionUsageToJSONTyped(value?: CompletionUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['prompt_tokens'],
        'completion_tokens': value['completion_tokens'],
        'total_tokens': value['total_tokens'],
        'prompt_tokens_details': CompletionUsagePromptTokensDetailsToJSON(value['prompt_tokens_details']),
        'completion_tokens_details': CompletionUsageCompletionTokensDetailsToJSON(value['completion_tokens_details']),
    };
}

