/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionUsagePromptTokensDetails
 */
export interface CompletionUsagePromptTokensDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsagePromptTokensDetails
     */
    cached_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionUsagePromptTokensDetails
     */
    audio_tokens?: number;
}

/**
 * Check if a given object implements the CompletionUsagePromptTokensDetails interface.
 */
export function instanceOfCompletionUsagePromptTokensDetails(value: object): value is CompletionUsagePromptTokensDetails {
    return true;
}

export function CompletionUsagePromptTokensDetailsFromJSON(json: any): CompletionUsagePromptTokensDetails {
    return CompletionUsagePromptTokensDetailsFromJSONTyped(json, false);
}

export function CompletionUsagePromptTokensDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionUsagePromptTokensDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'cached_tokens': json['cached_tokens'] == null ? undefined : json['cached_tokens'],
        'audio_tokens': json['audio_tokens'] == null ? undefined : json['audio_tokens'],
    };
}

export function CompletionUsagePromptTokensDetailsToJSON(json: any): CompletionUsagePromptTokensDetails {
    return CompletionUsagePromptTokensDetailsToJSONTyped(json, false);
}

export function CompletionUsagePromptTokensDetailsToJSONTyped(value?: CompletionUsagePromptTokensDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'cached_tokens': value['cached_tokens'],
        'audio_tokens': value['audio_tokens'],
    };
}

