/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInnerLogprobsContentInner
 */
export interface CreateChatCompletionResponseChoicesInnerLogprobsContentInner {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponseChoicesInnerLogprobsContentInner
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseChoicesInnerLogprobsContentInner
     */
    logprob: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateChatCompletionResponseChoicesInnerLogprobsContentInner
     */
    bytes?: Array<number> | null;
}

/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInnerLogprobsContentInner interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInnerLogprobsContentInner(value: object): value is CreateChatCompletionResponseChoicesInnerLogprobsContentInner {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('logprob' in value) || value['logprob'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSON(json: any): CreateChatCompletionResponseChoicesInnerLogprobsContentInner {
    return CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInnerLogprobsContentInner {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
        'logprob': json['logprob'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
    };
}

export function CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSON(json: any): CreateChatCompletionResponseChoicesInnerLogprobsContentInner {
    return CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSONTyped(value?: CreateChatCompletionResponseChoicesInnerLogprobsContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'token': value['token'],
        'logprob': value['logprob'],
        'bytes': value['bytes'],
    };
}

