/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestResponseFormat } from './CreateChatCompletionRequestResponseFormat';
import {
    CreateChatCompletionRequestResponseFormatFromJSON,
    CreateChatCompletionRequestResponseFormatFromJSONTyped,
    CreateChatCompletionRequestResponseFormatToJSON,
    CreateChatCompletionRequestResponseFormatToJSONTyped,
} from './CreateChatCompletionRequestResponseFormat';
import type { ChatCompletionMessage } from './ChatCompletionMessage';
import {
    ChatCompletionMessageFromJSON,
    ChatCompletionMessageFromJSONTyped,
    ChatCompletionMessageToJSON,
    ChatCompletionMessageToJSONTyped,
} from './ChatCompletionMessage';
import type { CreateChatCompletionRequestStreamOptions } from './CreateChatCompletionRequestStreamOptions';
import {
    CreateChatCompletionRequestStreamOptionsFromJSON,
    CreateChatCompletionRequestStreamOptionsFromJSONTyped,
    CreateChatCompletionRequestStreamOptionsToJSON,
    CreateChatCompletionRequestStreamOptionsToJSONTyped,
} from './CreateChatCompletionRequestStreamOptions';
import type { CreateChatCompletionRequestStop } from './CreateChatCompletionRequestStop';
import {
    CreateChatCompletionRequestStopFromJSON,
    CreateChatCompletionRequestStopFromJSONTyped,
    CreateChatCompletionRequestStopToJSON,
    CreateChatCompletionRequestStopToJSONTyped,
} from './CreateChatCompletionRequestStop';
import type { CreateChatCompletionRequestToolChoice } from './CreateChatCompletionRequestToolChoice';
import {
    CreateChatCompletionRequestToolChoiceFromJSON,
    CreateChatCompletionRequestToolChoiceFromJSONTyped,
    CreateChatCompletionRequestToolChoiceToJSON,
    CreateChatCompletionRequestToolChoiceToJSONTyped,
} from './CreateChatCompletionRequestToolChoice';
import type { CreateChatCompletionRequestToolsInner } from './CreateChatCompletionRequestToolsInner';
import {
    CreateChatCompletionRequestToolsInnerFromJSON,
    CreateChatCompletionRequestToolsInnerFromJSONTyped,
    CreateChatCompletionRequestToolsInnerToJSON,
    CreateChatCompletionRequestToolsInnerToJSONTyped,
} from './CreateChatCompletionRequestToolsInner';

/**
 * 
 * @export
 * @interface CreateChatCompletionRequest
 */
export interface CreateChatCompletionRequest {
    [key: string]: any | any;
    /**
     * ID of the model to use for the chat completion.
     * @type {string}
     * @memberof CreateChatCompletionRequest
     */
    model: string;
    /**
     * A list of messages comprising the conversation so far.
     * @type {Array<ChatCompletionMessage>}
     * @memberof CreateChatCompletionRequest
     */
    messages: Array<ChatCompletionMessage>;
    /**
     * If true, partial message deltas will be sent as server-sent events.
     * @type {boolean}
     * @memberof CreateChatCompletionRequest
     */
    stream?: boolean | null;
    /**
     * 
     * @type {CreateChatCompletionRequestStreamOptions}
     * @memberof CreateChatCompletionRequest
     */
    stream_options?: CreateChatCompletionRequestStreamOptions;
    /**
     * Sampling temperature between 0 and 2. Higher values make output more random.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    temperature?: number | null;
    /**
     * Nucleus sampling: consider tokens with top_p probability mass.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    top_p?: number | null;
    /**
     * How many chat completion choices to generate.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    n?: number | null;
    /**
     * Maximum number of tokens to generate. Deprecated in favor of max_completion_tokens.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     * @deprecated
     */
    max_tokens?: number | null;
    /**
     * Upper bound for tokens that can be generated, including visible output and reasoning tokens.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    max_completion_tokens?: number | null;
    /**
     * 
     * @type {CreateChatCompletionRequestStop}
     * @memberof CreateChatCompletionRequest
     */
    stop?: CreateChatCompletionRequestStop | null;
    /**
     * Number between -2.0 and 2.0. Positive values penalize tokens based on existing frequency.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    frequency_penalty?: number | null;
    /**
     * Number between -2.0 and 2.0. Positive values penalize tokens based on whether they appear in the text so far.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    presence_penalty?: number | null;
    /**
     * Whether to return log probabilities of the output tokens.
     * @type {boolean}
     * @memberof CreateChatCompletionRequest
     */
    logprobs?: boolean | null;
    /**
     * Number of most likely tokens to return at each position (0-20). Requires logprobs=true.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    top_logprobs?: number | null;
    /**
     * Map of token IDs to bias values (-100 to 100) to modify likelihood of specified tokens.
     * @type {{ [key: string]: number; }}
     * @memberof CreateChatCompletionRequest
     */
    logit_bias?: { [key: string]: number; };
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormat}
     * @memberof CreateChatCompletionRequest
     */
    response_format?: CreateChatCompletionRequestResponseFormat;
    /**
     * If specified, the system will attempt deterministic sampling. Determinism is not guaranteed.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    seed?: number | null;
    /**
     * A list of tools the model may call.
     * @type {Array<CreateChatCompletionRequestToolsInner>}
     * @memberof CreateChatCompletionRequest
     */
    tools?: Array<CreateChatCompletionRequestToolsInner>;
    /**
     * 
     * @type {CreateChatCompletionRequestToolChoice}
     * @memberof CreateChatCompletionRequest
     */
    tool_choice?: CreateChatCompletionRequestToolChoice;
    /**
     * Whether to enable parallel function calling during tool use.
     * @type {boolean}
     * @memberof CreateChatCompletionRequest
     */
    parallel_tool_calls?: boolean;
    /**
     * Constrains reasoning effort for reasoning models. One of: none, minimal, low, medium, high, xhigh.
     * @type {CreateChatCompletionRequestReasoningEffortEnum}
     * @memberof CreateChatCompletionRequest
     */
    reasoning_effort?: CreateChatCompletionRequestReasoningEffortEnum;
    /**
     * Number of highest probability tokens to keep for top-k sampling. -1 to disable.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    top_k?: number | null;
    /**
     * Minimum probability threshold relative to the top token. Tokens below this are filtered out. 0.0 to disable.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    min_p?: number | null;
    /**
     * Penalizes new tokens based on whether they appear in the generated text so far. Values > 1.0 penalize repetitions.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    repetition_penalty?: number | null;
    /**
     * Minimum number of tokens to generate before allowing a stop condition.
     * @type {number}
     * @memberof CreateChatCompletionRequest
     */
    min_tokens?: number;
    /**
     * If true, the prompt is prepended to the generated output.
     * @type {boolean}
     * @memberof CreateChatCompletionRequest
     */
    echo?: boolean;
    /**
     * A unique identifier representing your end-user.
     * @type {string}
     * @memberof CreateChatCompletionRequest
     */
    user?: string | null;
}


/**
 * @export
 */
export const CreateChatCompletionRequestReasoningEffortEnum = {
    None: 'none',
    Minimal: 'minimal',
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Xhigh: 'xhigh'
} as const;
export type CreateChatCompletionRequestReasoningEffortEnum = typeof CreateChatCompletionRequestReasoningEffortEnum[keyof typeof CreateChatCompletionRequestReasoningEffortEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequest interface.
 */
export function instanceOfCreateChatCompletionRequest(value: object): value is CreateChatCompletionRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestFromJSON(json: any): CreateChatCompletionRequest {
    return CreateChatCompletionRequestFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'model': json['model'],
        'messages': ((json['messages'] as Array<any>).map(ChatCompletionMessageFromJSON)),
        'stream': json['stream'] == null ? undefined : json['stream'],
        'stream_options': json['stream_options'] == null ? undefined : CreateChatCompletionRequestStreamOptionsFromJSON(json['stream_options']),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'top_p': json['top_p'] == null ? undefined : json['top_p'],
        'n': json['n'] == null ? undefined : json['n'],
        'max_tokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'max_completion_tokens': json['max_completion_tokens'] == null ? undefined : json['max_completion_tokens'],
        'stop': json['stop'] == null ? undefined : CreateChatCompletionRequestStopFromJSON(json['stop']),
        'frequency_penalty': json['frequency_penalty'] == null ? undefined : json['frequency_penalty'],
        'presence_penalty': json['presence_penalty'] == null ? undefined : json['presence_penalty'],
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
        'top_logprobs': json['top_logprobs'] == null ? undefined : json['top_logprobs'],
        'logit_bias': json['logit_bias'] == null ? undefined : json['logit_bias'],
        'response_format': json['response_format'] == null ? undefined : CreateChatCompletionRequestResponseFormatFromJSON(json['response_format']),
        'seed': json['seed'] == null ? undefined : json['seed'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(CreateChatCompletionRequestToolsInnerFromJSON)),
        'tool_choice': json['tool_choice'] == null ? undefined : CreateChatCompletionRequestToolChoiceFromJSON(json['tool_choice']),
        'parallel_tool_calls': json['parallel_tool_calls'] == null ? undefined : json['parallel_tool_calls'],
        'reasoning_effort': json['reasoning_effort'] == null ? undefined : json['reasoning_effort'],
        'top_k': json['top_k'] == null ? undefined : json['top_k'],
        'min_p': json['min_p'] == null ? undefined : json['min_p'],
        'repetition_penalty': json['repetition_penalty'] == null ? undefined : json['repetition_penalty'],
        'min_tokens': json['min_tokens'] == null ? undefined : json['min_tokens'],
        'echo': json['echo'] == null ? undefined : json['echo'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function CreateChatCompletionRequestToJSON(json: any): CreateChatCompletionRequest {
    return CreateChatCompletionRequestToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToJSONTyped(value?: CreateChatCompletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'model': value['model'],
        'messages': ((value['messages'] as Array<any>).map(ChatCompletionMessageToJSON)),
        'stream': value['stream'],
        'stream_options': CreateChatCompletionRequestStreamOptionsToJSON(value['stream_options']),
        'temperature': value['temperature'],
        'top_p': value['top_p'],
        'n': value['n'],
        'max_tokens': value['max_tokens'],
        'max_completion_tokens': value['max_completion_tokens'],
        'stop': CreateChatCompletionRequestStopToJSON(value['stop']),
        'frequency_penalty': value['frequency_penalty'],
        'presence_penalty': value['presence_penalty'],
        'logprobs': value['logprobs'],
        'top_logprobs': value['top_logprobs'],
        'logit_bias': value['logit_bias'],
        'response_format': CreateChatCompletionRequestResponseFormatToJSON(value['response_format']),
        'seed': value['seed'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(CreateChatCompletionRequestToolsInnerToJSON)),
        'tool_choice': CreateChatCompletionRequestToolChoiceToJSON(value['tool_choice']),
        'parallel_tool_calls': value['parallel_tool_calls'],
        'reasoning_effort': value['reasoning_effort'],
        'top_k': value['top_k'],
        'min_p': value['min_p'],
        'repetition_penalty': value['repetition_penalty'],
        'min_tokens': value['min_tokens'],
        'echo': value['echo'],
        'user': value['user'],
    };
}

