/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestToolsInnerFunction } from './CreateChatCompletionRequestToolsInnerFunction';
import {
    CreateChatCompletionRequestToolsInnerFunctionFromJSON,
    CreateChatCompletionRequestToolsInnerFunctionFromJSONTyped,
    CreateChatCompletionRequestToolsInnerFunctionToJSON,
    CreateChatCompletionRequestToolsInnerFunctionToJSONTyped,
} from './CreateChatCompletionRequestToolsInnerFunction';

/**
 * 
 * @export
 * @interface CreateChatCompletionRequestToolsInner
 */
export interface CreateChatCompletionRequestToolsInner {
    /**
     * 
     * @type {CreateChatCompletionRequestToolsInnerTypeEnum}
     * @memberof CreateChatCompletionRequestToolsInner
     */
    type: CreateChatCompletionRequestToolsInnerTypeEnum;
    /**
     * 
     * @type {CreateChatCompletionRequestToolsInnerFunction}
     * @memberof CreateChatCompletionRequestToolsInner
     */
    _function: CreateChatCompletionRequestToolsInnerFunction;
}


/**
 * @export
 */
export const CreateChatCompletionRequestToolsInnerTypeEnum = {
    Function: 'function'
} as const;
export type CreateChatCompletionRequestToolsInnerTypeEnum = typeof CreateChatCompletionRequestToolsInnerTypeEnum[keyof typeof CreateChatCompletionRequestToolsInnerTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestToolsInner interface.
 */
export function instanceOfCreateChatCompletionRequestToolsInner(value: object): value is CreateChatCompletionRequestToolsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestToolsInnerFromJSON(json: any): CreateChatCompletionRequestToolsInner {
    return CreateChatCompletionRequestToolsInnerFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': CreateChatCompletionRequestToolsInnerFunctionFromJSON(json['function']),
    };
}

export function CreateChatCompletionRequestToolsInnerToJSON(json: any): CreateChatCompletionRequestToolsInner {
    return CreateChatCompletionRequestToolsInnerToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolsInnerToJSONTyped(value?: CreateChatCompletionRequestToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': CreateChatCompletionRequestToolsInnerFunctionToJSON(value['_function']),
    };
}

