/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestStop
 */
export interface CreateChatCompletionRequestStop {
}

/**
 * Check if a given object implements the CreateChatCompletionRequestStop interface.
 */
export function instanceOfCreateChatCompletionRequestStop(value: object): value is CreateChatCompletionRequestStop {
    return true;
}

export function CreateChatCompletionRequestStopFromJSON(json: any): CreateChatCompletionRequestStop {
    return CreateChatCompletionRequestStopFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestStopFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestStop {
    return json;
}

export function CreateChatCompletionRequestStopToJSON(json: any): CreateChatCompletionRequestStop {
    return CreateChatCompletionRequestStopToJSONTyped(json, false);
}

export function CreateChatCompletionRequestStopToJSONTyped(value?: CreateChatCompletionRequestStop | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

