/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseRequestToolChoiceAnyOf
 */
export interface CreateResponseRequestToolChoiceAnyOf {
    /**
     * 
     * @type {CreateResponseRequestToolChoiceAnyOfTypeEnum}
     * @memberof CreateResponseRequestToolChoiceAnyOf
     */
    type: CreateResponseRequestToolChoiceAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestToolChoiceAnyOf
     */
    name: string;
}


/**
 * @export
 */
export const CreateResponseRequestToolChoiceAnyOfTypeEnum = {
    Function: 'function'
} as const;
export type CreateResponseRequestToolChoiceAnyOfTypeEnum = typeof CreateResponseRequestToolChoiceAnyOfTypeEnum[keyof typeof CreateResponseRequestToolChoiceAnyOfTypeEnum];


/**
 * Check if a given object implements the CreateResponseRequestToolChoiceAnyOf interface.
 */
export function instanceOfCreateResponseRequestToolChoiceAnyOf(value: object): value is CreateResponseRequestToolChoiceAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateResponseRequestToolChoiceAnyOfFromJSON(json: any): CreateResponseRequestToolChoiceAnyOf {
    return CreateResponseRequestToolChoiceAnyOfFromJSONTyped(json, false);
}

export function CreateResponseRequestToolChoiceAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestToolChoiceAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
    };
}

export function CreateResponseRequestToolChoiceAnyOfToJSON(json: any): CreateResponseRequestToolChoiceAnyOf {
    return CreateResponseRequestToolChoiceAnyOfToJSONTyped(json, false);
}

export function CreateResponseRequestToolChoiceAnyOfToJSONTyped(value?: CreateResponseRequestToolChoiceAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
    };
}

