/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInnerAnyOf1
 */
export interface CreateResponseResponseOutputInnerAnyOf1 {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    id: string;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOf1TypeEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    type: CreateResponseResponseOutputInnerAnyOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    call_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    arguments: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf1
     */
    status?: string;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOf1TypeEnum = {
    FunctionCall: 'function_call'
} as const;
export type CreateResponseResponseOutputInnerAnyOf1TypeEnum = typeof CreateResponseResponseOutputInnerAnyOf1TypeEnum[keyof typeof CreateResponseResponseOutputInnerAnyOf1TypeEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInnerAnyOf1 interface.
 */
export function instanceOfCreateResponseResponseOutputInnerAnyOf1(value: object): value is CreateResponseResponseOutputInnerAnyOf1 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('call_id' in value) || value['call_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('arguments' in value) || value['arguments'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerAnyOf1FromJSON(json: any): CreateResponseResponseOutputInnerAnyOf1 {
    return CreateResponseResponseOutputInnerAnyOf1FromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInnerAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': json['type'],
        'call_id': json['call_id'],
        'name': json['name'],
        'arguments': json['arguments'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CreateResponseResponseOutputInnerAnyOf1ToJSON(json: any): CreateResponseResponseOutputInnerAnyOf1 {
    return CreateResponseResponseOutputInnerAnyOf1ToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOf1ToJSONTyped(value?: CreateResponseResponseOutputInnerAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'type': value['type'],
        'call_id': value['call_id'],
        'name': value['name'],
        'arguments': value['arguments'],
        'status': value['status'],
    };
}

