/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestResponseFormatAnyOf
 */
export interface CreateChatCompletionRequestResponseFormatAnyOf {
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatAnyOfTypeEnum}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf
     */
    type: CreateChatCompletionRequestResponseFormatAnyOfTypeEnum;
}


/**
 * @export
 */
export const CreateChatCompletionRequestResponseFormatAnyOfTypeEnum = {
    Text: 'text'
} as const;
export type CreateChatCompletionRequestResponseFormatAnyOfTypeEnum = typeof CreateChatCompletionRequestResponseFormatAnyOfTypeEnum[keyof typeof CreateChatCompletionRequestResponseFormatAnyOfTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestResponseFormatAnyOf interface.
 */
export function instanceOfCreateChatCompletionRequestResponseFormatAnyOf(value: object): value is CreateChatCompletionRequestResponseFormatAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestResponseFormatAnyOfFromJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf {
    return CreateChatCompletionRequestResponseFormatAnyOfFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestResponseFormatAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function CreateChatCompletionRequestResponseFormatAnyOfToJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf {
    return CreateChatCompletionRequestResponseFormatAnyOfToJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOfToJSONTyped(value?: CreateChatCompletionRequestResponseFormatAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

