/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseRequestTextFormat } from './CreateResponseRequestTextFormat';
import {
    CreateResponseRequestTextFormatFromJSON,
    CreateResponseRequestTextFormatFromJSONTyped,
    CreateResponseRequestTextFormatToJSON,
    CreateResponseRequestTextFormatToJSONTyped,
} from './CreateResponseRequestTextFormat';

/**
 * Configuration for text response format (text, json_object, json_schema).
 * @export
 * @interface CreateResponseRequestText
 */
export interface CreateResponseRequestText {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateResponseRequestTextFormat}
     * @memberof CreateResponseRequestText
     */
    format?: CreateResponseRequestTextFormat;
}

/**
 * Check if a given object implements the CreateResponseRequestText interface.
 */
export function instanceOfCreateResponseRequestText(value: object): value is CreateResponseRequestText {
    return true;
}

export function CreateResponseRequestTextFromJSON(json: any): CreateResponseRequestText {
    return CreateResponseRequestTextFromJSONTyped(json, false);
}

export function CreateResponseRequestTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestText {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'format': json['format'] == null ? undefined : CreateResponseRequestTextFormatFromJSON(json['format']),
    };
}

export function CreateResponseRequestTextToJSON(json: any): CreateResponseRequestText {
    return CreateResponseRequestTextToJSONTyped(json, false);
}

export function CreateResponseRequestTextToJSONTyped(value?: CreateResponseRequestText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'format': CreateResponseRequestTextFormatToJSON(value['format']),
    };
}

