/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestToolChoiceAnyOfFunction
 */
export interface CreateChatCompletionRequestToolChoiceAnyOfFunction {
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestToolChoiceAnyOfFunction
     */
    name: string;
}

/**
 * Check if a given object implements the CreateChatCompletionRequestToolChoiceAnyOfFunction interface.
 */
export function instanceOfCreateChatCompletionRequestToolChoiceAnyOfFunction(value: object): value is CreateChatCompletionRequestToolChoiceAnyOfFunction {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSON(json: any): CreateChatCompletionRequestToolChoiceAnyOfFunction {
    return CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestToolChoiceAnyOfFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSON(json: any): CreateChatCompletionRequestToolChoiceAnyOfFunction {
    return CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSONTyped(value?: CreateChatCompletionRequestToolChoiceAnyOfFunction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

