/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseRequestToolsInner
 */
export interface CreateResponseRequestToolsInner {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateResponseRequestToolsInnerTypeEnum}
     * @memberof CreateResponseRequestToolsInner
     */
    type: CreateResponseRequestToolsInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestToolsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestToolsInner
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateResponseRequestToolsInner
     */
    parameters?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateResponseRequestToolsInner
     */
    strict?: boolean | null;
}


/**
 * @export
 */
export const CreateResponseRequestToolsInnerTypeEnum = {
    Function: 'function'
} as const;
export type CreateResponseRequestToolsInnerTypeEnum = typeof CreateResponseRequestToolsInnerTypeEnum[keyof typeof CreateResponseRequestToolsInnerTypeEnum];


/**
 * Check if a given object implements the CreateResponseRequestToolsInner interface.
 */
export function instanceOfCreateResponseRequestToolsInner(value: object): value is CreateResponseRequestToolsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateResponseRequestToolsInnerFromJSON(json: any): CreateResponseRequestToolsInner {
    return CreateResponseRequestToolsInnerFromJSONTyped(json, false);
}

export function CreateResponseRequestToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function CreateResponseRequestToolsInnerToJSON(json: any): CreateResponseRequestToolsInner {
    return CreateResponseRequestToolsInnerToJSONTyped(json, false);
}

export function CreateResponseRequestToolsInnerToJSONTyped(value?: CreateResponseRequestToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
        'strict': value['strict'],
    };
}

