/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseChoicesInnerLogprobsContentInner } from './CreateChatCompletionResponseChoicesInnerLogprobsContentInner';
import {
    CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSON,
    CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSON,
    CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSONTyped,
} from './CreateChatCompletionResponseChoicesInnerLogprobsContentInner';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInnerLogprobs
 */
export interface CreateChatCompletionResponseChoicesInnerLogprobs {
    /**
     * 
     * @type {Array<CreateChatCompletionResponseChoicesInnerLogprobsContentInner>}
     * @memberof CreateChatCompletionResponseChoicesInnerLogprobs
     */
    content: Array<CreateChatCompletionResponseChoicesInnerLogprobsContentInner> | null;
    /**
     * 
     * @type {Array<CreateChatCompletionResponseChoicesInnerLogprobsContentInner>}
     * @memberof CreateChatCompletionResponseChoicesInnerLogprobs
     */
    refusal: Array<CreateChatCompletionResponseChoicesInnerLogprobsContentInner> | null;
}

/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInnerLogprobs interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInnerLogprobs(value: object): value is CreateChatCompletionResponseChoicesInnerLogprobs {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerLogprobsFromJSON(json: any): CreateChatCompletionResponseChoicesInnerLogprobs {
    return CreateChatCompletionResponseChoicesInnerLogprobsFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerLogprobsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInnerLogprobs {
    if (json == null) {
        return json;
    }
    return {
        
        'content': (json['content'] == null ? null : (json['content'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSON)),
        'refusal': (json['refusal'] == null ? null : (json['refusal'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerLogprobsContentInnerFromJSON)),
    };
}

export function CreateChatCompletionResponseChoicesInnerLogprobsToJSON(json: any): CreateChatCompletionResponseChoicesInnerLogprobs {
    return CreateChatCompletionResponseChoicesInnerLogprobsToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerLogprobsToJSONTyped(value?: CreateChatCompletionResponseChoicesInnerLogprobs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': (value['content'] == null ? null : (value['content'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSON)),
        'refusal': (value['refusal'] == null ? null : (value['refusal'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerLogprobsContentInnerToJSON)),
    };
}

