/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema } from './CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema';
import {
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema';

/**
 * 
 * @export
 * @interface CreateChatCompletionRequestResponseFormatAnyOf2
 */
export interface CreateChatCompletionRequestResponseFormatAnyOf2 {
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2
     */
    type: CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum;
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2
     */
    json_schema: CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema;
}


/**
 * @export
 */
export const CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum = {
    JsonSchema: 'json_schema'
} as const;
export type CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum = typeof CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum[keyof typeof CreateChatCompletionRequestResponseFormatAnyOf2TypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestResponseFormatAnyOf2 interface.
 */
export function instanceOfCreateChatCompletionRequestResponseFormatAnyOf2(value: object): value is CreateChatCompletionRequestResponseFormatAnyOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('json_schema' in value) || value['json_schema'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestResponseFormatAnyOf2FromJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf2 {
    return CreateChatCompletionRequestResponseFormatAnyOf2FromJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestResponseFormatAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'json_schema': CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSON(json['json_schema']),
    };
}

export function CreateChatCompletionRequestResponseFormatAnyOf2ToJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf2 {
    return CreateChatCompletionRequestResponseFormatAnyOf2ToJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf2ToJSONTyped(value?: CreateChatCompletionRequestResponseFormatAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'json_schema': CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSON(value['json_schema']),
    };
}

