/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestToolsInnerFunction
 */
export interface CreateChatCompletionRequestToolsInnerFunction {
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestToolsInnerFunction
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestToolsInnerFunction
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateChatCompletionRequestToolsInnerFunction
     */
    parameters?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateChatCompletionRequestToolsInnerFunction
     */
    strict?: boolean | null;
}

/**
 * Check if a given object implements the CreateChatCompletionRequestToolsInnerFunction interface.
 */
export function instanceOfCreateChatCompletionRequestToolsInnerFunction(value: object): value is CreateChatCompletionRequestToolsInnerFunction {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestToolsInnerFunctionFromJSON(json: any): CreateChatCompletionRequestToolsInnerFunction {
    return CreateChatCompletionRequestToolsInnerFunctionFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolsInnerFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestToolsInnerFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function CreateChatCompletionRequestToolsInnerFunctionToJSON(json: any): CreateChatCompletionRequestToolsInnerFunction {
    return CreateChatCompletionRequestToolsInnerFunctionToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolsInnerFunctionToJSONTyped(value?: CreateChatCompletionRequestToolsInnerFunction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
        'strict': value['strict'],
    };
}

