/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseChoicesInner } from './CreateChatCompletionResponseChoicesInner';
import {
    CreateChatCompletionResponseChoicesInnerFromJSON,
    CreateChatCompletionResponseChoicesInnerFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerToJSON,
    CreateChatCompletionResponseChoicesInnerToJSONTyped,
} from './CreateChatCompletionResponseChoicesInner';
import type { CompletionUsage } from './CompletionUsage';
import {
    CompletionUsageFromJSON,
    CompletionUsageFromJSONTyped,
    CompletionUsageToJSON,
    CompletionUsageToJSONTyped,
} from './CompletionUsage';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponse
 */
export interface CreateChatCompletionResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    id: string;
    /**
     * 
     * @type {CreateChatCompletionResponseObjectEnum}
     * @memberof CreateChatCompletionResponse
     */
    object: CreateChatCompletionResponseObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    model: string;
    /**
     * 
     * @type {Array<CreateChatCompletionResponseChoicesInner>}
     * @memberof CreateChatCompletionResponse
     */
    choices: Array<CreateChatCompletionResponseChoicesInner>;
    /**
     * 
     * @type {CompletionUsage}
     * @memberof CreateChatCompletionResponse
     */
    usage?: CompletionUsage;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse
     */
    system_fingerprint?: string;
}


/**
 * @export
 */
export const CreateChatCompletionResponseObjectEnum = {
    ChatCompletion: 'chat.completion'
} as const;
export type CreateChatCompletionResponseObjectEnum = typeof CreateChatCompletionResponseObjectEnum[keyof typeof CreateChatCompletionResponseObjectEnum];


/**
 * Check if a given object implements the CreateChatCompletionResponse interface.
 */
export function instanceOfCreateChatCompletionResponse(value: object): value is CreateChatCompletionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseFromJSON(json: any): CreateChatCompletionResponse {
    return CreateChatCompletionResponseFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerFromJSON)),
        'usage': json['usage'] == null ? undefined : CompletionUsageFromJSON(json['usage']),
        'system_fingerprint': json['system_fingerprint'] == null ? undefined : json['system_fingerprint'],
    };
}

export function CreateChatCompletionResponseToJSON(json: any): CreateChatCompletionResponse {
    return CreateChatCompletionResponseToJSONTyped(json, false);
}

export function CreateChatCompletionResponseToJSONTyped(value?: CreateChatCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerToJSON)),
        'usage': CompletionUsageToJSON(value['usage']),
        'system_fingerprint': value['system_fingerprint'],
    };
}

