/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseRequestTextFormatAnyOf } from './CreateResponseRequestTextFormatAnyOf';
import {
    CreateResponseRequestTextFormatAnyOfFromJSON,
    CreateResponseRequestTextFormatAnyOfFromJSONTyped,
    CreateResponseRequestTextFormatAnyOfToJSON,
    CreateResponseRequestTextFormatAnyOfToJSONTyped,
} from './CreateResponseRequestTextFormatAnyOf';
import type { CreateChatCompletionRequestResponseFormatAnyOf } from './CreateChatCompletionRequestResponseFormatAnyOf';
import {
    CreateChatCompletionRequestResponseFormatAnyOfFromJSON,
    CreateChatCompletionRequestResponseFormatAnyOfFromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOfToJSON,
    CreateChatCompletionRequestResponseFormatAnyOfToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf';
import type { CreateChatCompletionRequestResponseFormatAnyOf1 } from './CreateChatCompletionRequestResponseFormatAnyOf1';
import {
    CreateChatCompletionRequestResponseFormatAnyOf1FromJSON,
    CreateChatCompletionRequestResponseFormatAnyOf1FromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOf1ToJSON,
    CreateChatCompletionRequestResponseFormatAnyOf1ToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf1';

/**
 * 
 * @export
 * @interface CreateResponseRequestTextFormat
 */
export interface CreateResponseRequestTextFormat {
    /**
     * 
     * @type {CreateResponseRequestTextFormatTypeEnum}
     * @memberof CreateResponseRequestTextFormat
     */
    type: CreateResponseRequestTextFormatTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestTextFormat
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestTextFormat
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateResponseRequestTextFormat
     */
    schema?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateResponseRequestTextFormat
     */
    strict?: boolean;
}


/**
 * @export
 */
export const CreateResponseRequestTextFormatTypeEnum = {
    Text: 'text',
    JsonObject: 'json_object',
    JsonSchema: 'json_schema'
} as const;
export type CreateResponseRequestTextFormatTypeEnum = typeof CreateResponseRequestTextFormatTypeEnum[keyof typeof CreateResponseRequestTextFormatTypeEnum];


/**
 * Check if a given object implements the CreateResponseRequestTextFormat interface.
 */
export function instanceOfCreateResponseRequestTextFormat(value: object): value is CreateResponseRequestTextFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateResponseRequestTextFormatFromJSON(json: any): CreateResponseRequestTextFormat {
    return CreateResponseRequestTextFormatFromJSONTyped(json, false);
}

export function CreateResponseRequestTextFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestTextFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function CreateResponseRequestTextFormatToJSON(json: any): CreateResponseRequestTextFormat {
    return CreateResponseRequestTextFormatToJSONTyped(json, false);
}

export function CreateResponseRequestTextFormatToJSONTyped(value?: CreateResponseRequestTextFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'description': value['description'],
        'schema': value['schema'],
        'strict': value['strict'],
    };
}

