/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseRequestToolChoiceAnyOf } from './CreateResponseRequestToolChoiceAnyOf';
import {
    CreateResponseRequestToolChoiceAnyOfFromJSON,
    CreateResponseRequestToolChoiceAnyOfFromJSONTyped,
    CreateResponseRequestToolChoiceAnyOfToJSON,
    CreateResponseRequestToolChoiceAnyOfToJSONTyped,
} from './CreateResponseRequestToolChoiceAnyOf';

/**
 * How the model should select which tool to use. "none", "auto", "required", or a specific tool.
 * @export
 * @interface CreateResponseRequestToolChoice
 */
export interface CreateResponseRequestToolChoice {
    /**
     * 
     * @type {CreateResponseRequestToolChoiceTypeEnum}
     * @memberof CreateResponseRequestToolChoice
     */
    type: CreateResponseRequestToolChoiceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestToolChoice
     */
    name: string;
}


/**
 * @export
 */
export const CreateResponseRequestToolChoiceTypeEnum = {
    Function: 'function'
} as const;
export type CreateResponseRequestToolChoiceTypeEnum = typeof CreateResponseRequestToolChoiceTypeEnum[keyof typeof CreateResponseRequestToolChoiceTypeEnum];


/**
 * Check if a given object implements the CreateResponseRequestToolChoice interface.
 */
export function instanceOfCreateResponseRequestToolChoice(value: object): value is CreateResponseRequestToolChoice {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateResponseRequestToolChoiceFromJSON(json: any): CreateResponseRequestToolChoice {
    return CreateResponseRequestToolChoiceFromJSONTyped(json, false);
}

export function CreateResponseRequestToolChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestToolChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
    };
}

export function CreateResponseRequestToolChoiceToJSON(json: any): CreateResponseRequestToolChoice {
    return CreateResponseRequestToolChoiceToJSONTyped(json, false);
}

export function CreateResponseRequestToolChoiceToJSONTyped(value?: CreateResponseRequestToolChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
    };
}

