/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseRequestTextFormatAnyOf
 */
export interface CreateResponseRequestTextFormatAnyOf {
    /**
     * 
     * @type {CreateResponseRequestTextFormatAnyOfTypeEnum}
     * @memberof CreateResponseRequestTextFormatAnyOf
     */
    type: CreateResponseRequestTextFormatAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestTextFormatAnyOf
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseRequestTextFormatAnyOf
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateResponseRequestTextFormatAnyOf
     */
    schema?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateResponseRequestTextFormatAnyOf
     */
    strict?: boolean | null;
}


/**
 * @export
 */
export const CreateResponseRequestTextFormatAnyOfTypeEnum = {
    JsonSchema: 'json_schema'
} as const;
export type CreateResponseRequestTextFormatAnyOfTypeEnum = typeof CreateResponseRequestTextFormatAnyOfTypeEnum[keyof typeof CreateResponseRequestTextFormatAnyOfTypeEnum];


/**
 * Check if a given object implements the CreateResponseRequestTextFormatAnyOf interface.
 */
export function instanceOfCreateResponseRequestTextFormatAnyOf(value: object): value is CreateResponseRequestTextFormatAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateResponseRequestTextFormatAnyOfFromJSON(json: any): CreateResponseRequestTextFormatAnyOf {
    return CreateResponseRequestTextFormatAnyOfFromJSONTyped(json, false);
}

export function CreateResponseRequestTextFormatAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestTextFormatAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function CreateResponseRequestTextFormatAnyOfToJSON(json: any): CreateResponseRequestTextFormatAnyOf {
    return CreateResponseRequestTextFormatAnyOfToJSONTyped(json, false);
}

export function CreateResponseRequestTextFormatAnyOfToJSONTyped(value?: CreateResponseRequestTextFormatAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'description': value['description'],
        'schema': value['schema'],
        'strict': value['strict'],
    };
}

