/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details about why the response is incomplete.
 * @export
 * @interface CreateResponseResponseIncompleteDetails
 */
export interface CreateResponseResponseIncompleteDetails {
    /**
     * 
     * @type {CreateResponseResponseIncompleteDetailsReasonEnum}
     * @memberof CreateResponseResponseIncompleteDetails
     */
    reason: CreateResponseResponseIncompleteDetailsReasonEnum;
}


/**
 * @export
 */
export const CreateResponseResponseIncompleteDetailsReasonEnum = {
    MaxOutputTokens: 'max_output_tokens',
    ContentFilter: 'content_filter'
} as const;
export type CreateResponseResponseIncompleteDetailsReasonEnum = typeof CreateResponseResponseIncompleteDetailsReasonEnum[keyof typeof CreateResponseResponseIncompleteDetailsReasonEnum];


/**
 * Check if a given object implements the CreateResponseResponseIncompleteDetails interface.
 */
export function instanceOfCreateResponseResponseIncompleteDetails(value: object): value is CreateResponseResponseIncompleteDetails {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function CreateResponseResponseIncompleteDetailsFromJSON(json: any): CreateResponseResponseIncompleteDetails {
    return CreateResponseResponseIncompleteDetailsFromJSONTyped(json, false);
}

export function CreateResponseResponseIncompleteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseIncompleteDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function CreateResponseResponseIncompleteDetailsToJSON(json: any): CreateResponseResponseIncompleteDetails {
    return CreateResponseResponseIncompleteDetailsToJSONTyped(json, false);
}

export function CreateResponseResponseIncompleteDetailsToJSONTyped(value?: CreateResponseResponseIncompleteDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

