/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf
 */
export interface CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf
     */
    type: CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf
     */
    text: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf
     */
    annotations?: Array<{ [key: string]: any; }>;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum = {
    OutputText: 'output_text'
} as const;
export type CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum = typeof CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum[keyof typeof CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfTypeEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf interface.
 */
export function instanceOfCreateResponseResponseOutputInnerAnyOfContentInnerAnyOf(value: object): value is CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfFromJSON(json: any): CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf {
    return CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfFromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'text': json['text'],
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
    };
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfToJSON(json: any): CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf {
    return CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfToJSONTyped(value?: CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'text': value['text'],
        'annotations': value['annotations'],
    };
}

