/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error details if the response generation failed.
 * @export
 * @interface CreateResponseResponseError
 */
export interface CreateResponseResponseError {
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseError
     */
    message: string;
}

/**
 * Check if a given object implements the CreateResponseResponseError interface.
 */
export function instanceOfCreateResponseResponseError(value: object): value is CreateResponseResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateResponseResponseErrorFromJSON(json: any): CreateResponseResponseError {
    return CreateResponseResponseErrorFromJSONTyped(json, false);
}

export function CreateResponseResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function CreateResponseResponseErrorToJSON(json: any): CreateResponseResponseError {
    return CreateResponseResponseErrorToJSONTyped(json, false);
}

export function CreateResponseResponseErrorToJSONTyped(value?: CreateResponseResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

