/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestResponseFormatAnyOf1
 */
export interface CreateChatCompletionRequestResponseFormatAnyOf1 {
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf1
     */
    type: CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum;
}


/**
 * @export
 */
export const CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum = {
    JsonObject: 'json_object'
} as const;
export type CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum = typeof CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum[keyof typeof CreateChatCompletionRequestResponseFormatAnyOf1TypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestResponseFormatAnyOf1 interface.
 */
export function instanceOfCreateChatCompletionRequestResponseFormatAnyOf1(value: object): value is CreateChatCompletionRequestResponseFormatAnyOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestResponseFormatAnyOf1FromJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf1 {
    return CreateChatCompletionRequestResponseFormatAnyOf1FromJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestResponseFormatAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function CreateChatCompletionRequestResponseFormatAnyOf1ToJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf1 {
    return CreateChatCompletionRequestResponseFormatAnyOf1ToJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf1ToJSONTyped(value?: CreateChatCompletionRequestResponseFormatAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

