/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestStreamOptions } from './CreateChatCompletionRequestStreamOptions';
import {
    CreateChatCompletionRequestStreamOptionsFromJSON,
    CreateChatCompletionRequestStreamOptionsFromJSONTyped,
    CreateChatCompletionRequestStreamOptionsToJSON,
    CreateChatCompletionRequestStreamOptionsToJSONTyped,
} from './CreateChatCompletionRequestStreamOptions';
import type { CreateChatCompletionRequestStop } from './CreateChatCompletionRequestStop';
import {
    CreateChatCompletionRequestStopFromJSON,
    CreateChatCompletionRequestStopFromJSONTyped,
    CreateChatCompletionRequestStopToJSON,
    CreateChatCompletionRequestStopToJSONTyped,
} from './CreateChatCompletionRequestStop';
import type { CreateCompletionRequestPrompt } from './CreateCompletionRequestPrompt';
import {
    CreateCompletionRequestPromptFromJSON,
    CreateCompletionRequestPromptFromJSONTyped,
    CreateCompletionRequestPromptToJSON,
    CreateCompletionRequestPromptToJSONTyped,
} from './CreateCompletionRequestPrompt';

/**
 * 
 * @export
 * @interface CreateCompletionRequest
 */
export interface CreateCompletionRequest {
    [key: string]: any | any;
    /**
     * ID of the model to use for the completion.
     * @type {string}
     * @memberof CreateCompletionRequest
     */
    model: string;
    /**
     * 
     * @type {CreateCompletionRequestPrompt}
     * @memberof CreateCompletionRequest
     */
    prompt: CreateCompletionRequestPrompt;
    /**
     * If true, partial completions will be sent as server-sent events.
     * @type {boolean}
     * @memberof CreateCompletionRequest
     */
    stream?: boolean | null;
    /**
     * 
     * @type {CreateChatCompletionRequestStreamOptions}
     * @memberof CreateCompletionRequest
     */
    stream_options?: CreateChatCompletionRequestStreamOptions;
    /**
     * Sampling temperature between 0 and 2.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    temperature?: number | null;
    /**
     * Nucleus sampling: consider tokens with top_p probability mass.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    top_p?: number | null;
    /**
     * How many completions to generate for each prompt.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    n?: number | null;
    /**
     * Maximum number of tokens to generate.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    max_tokens?: number | null;
    /**
     * 
     * @type {CreateChatCompletionRequestStop}
     * @memberof CreateCompletionRequest
     */
    stop?: CreateChatCompletionRequestStop | null;
    /**
     * Penalizes tokens based on existing frequency in the text so far.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    frequency_penalty?: number | null;
    /**
     * Penalizes tokens based on whether they appear in the text so far.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    presence_penalty?: number | null;
    /**
     * Include the log probabilities on the most likely output tokens (0-5).
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    logprobs?: number | null;
    /**
     * Echo back the prompt in addition to the completion.
     * @type {boolean}
     * @memberof CreateCompletionRequest
     */
    echo?: boolean | null;
    /**
     * Generates best_of completions server-side and returns the best one. Cannot be used with stream.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    best_of?: number | null;
    /**
     * The suffix that comes after the completion.
     * @type {string}
     * @memberof CreateCompletionRequest
     */
    suffix?: string | null;
    /**
     * If specified, the system will attempt deterministic sampling.
     * @type {number}
     * @memberof CreateCompletionRequest
     */
    seed?: number | null;
    /**
     * A unique identifier representing your end-user.
     * @type {string}
     * @memberof CreateCompletionRequest
     */
    user?: string | null;
}

/**
 * Check if a given object implements the CreateCompletionRequest interface.
 */
export function instanceOfCreateCompletionRequest(value: object): value is CreateCompletionRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function CreateCompletionRequestFromJSON(json: any): CreateCompletionRequest {
    return CreateCompletionRequestFromJSONTyped(json, false);
}

export function CreateCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'model': json['model'],
        'prompt': CreateCompletionRequestPromptFromJSON(json['prompt']),
        'stream': json['stream'] == null ? undefined : json['stream'],
        'stream_options': json['stream_options'] == null ? undefined : CreateChatCompletionRequestStreamOptionsFromJSON(json['stream_options']),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'top_p': json['top_p'] == null ? undefined : json['top_p'],
        'n': json['n'] == null ? undefined : json['n'],
        'max_tokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'stop': json['stop'] == null ? undefined : CreateChatCompletionRequestStopFromJSON(json['stop']),
        'frequency_penalty': json['frequency_penalty'] == null ? undefined : json['frequency_penalty'],
        'presence_penalty': json['presence_penalty'] == null ? undefined : json['presence_penalty'],
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
        'echo': json['echo'] == null ? undefined : json['echo'],
        'best_of': json['best_of'] == null ? undefined : json['best_of'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function CreateCompletionRequestToJSON(json: any): CreateCompletionRequest {
    return CreateCompletionRequestToJSONTyped(json, false);
}

export function CreateCompletionRequestToJSONTyped(value?: CreateCompletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'model': value['model'],
        'prompt': CreateCompletionRequestPromptToJSON(value['prompt']),
        'stream': value['stream'],
        'stream_options': CreateChatCompletionRequestStreamOptionsToJSON(value['stream_options']),
        'temperature': value['temperature'],
        'top_p': value['top_p'],
        'n': value['n'],
        'max_tokens': value['max_tokens'],
        'stop': CreateChatCompletionRequestStopToJSON(value['stop']),
        'frequency_penalty': value['frequency_penalty'],
        'presence_penalty': value['presence_penalty'],
        'logprobs': value['logprobs'],
        'echo': value['echo'],
        'best_of': value['best_of'],
        'suffix': value['suffix'],
        'seed': value['seed'],
        'user': value['user'],
    };
}

