/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInnerAnyOf2
 */
export interface CreateResponseResponseOutputInnerAnyOf2 {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf2
     */
    id: string;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOf2TypeEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOf2
     */
    type: CreateResponseResponseOutputInnerAnyOf2TypeEnum;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreateResponseResponseOutputInnerAnyOf2
     */
    summary?: Array<{ [key: string]: any; }>;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOf2TypeEnum = {
    Reasoning: 'reasoning'
} as const;
export type CreateResponseResponseOutputInnerAnyOf2TypeEnum = typeof CreateResponseResponseOutputInnerAnyOf2TypeEnum[keyof typeof CreateResponseResponseOutputInnerAnyOf2TypeEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInnerAnyOf2 interface.
 */
export function instanceOfCreateResponseResponseOutputInnerAnyOf2(value: object): value is CreateResponseResponseOutputInnerAnyOf2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerAnyOf2FromJSON(json: any): CreateResponseResponseOutputInnerAnyOf2 {
    return CreateResponseResponseOutputInnerAnyOf2FromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInnerAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': json['type'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function CreateResponseResponseOutputInnerAnyOf2ToJSON(json: any): CreateResponseResponseOutputInnerAnyOf2 {
    return CreateResponseResponseOutputInnerAnyOf2ToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOf2ToJSONTyped(value?: CreateResponseResponseOutputInnerAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'type': value['type'],
        'summary': value['summary'],
    };
}

