/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseChoicesInnerLogprobs } from './CreateChatCompletionResponseChoicesInnerLogprobs';
import {
    CreateChatCompletionResponseChoicesInnerLogprobsFromJSON,
    CreateChatCompletionResponseChoicesInnerLogprobsFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerLogprobsToJSON,
    CreateChatCompletionResponseChoicesInnerLogprobsToJSONTyped,
} from './CreateChatCompletionResponseChoicesInnerLogprobs';
import type { CreateChatCompletionResponseChoicesInnerMessage } from './CreateChatCompletionResponseChoicesInnerMessage';
import {
    CreateChatCompletionResponseChoicesInnerMessageFromJSON,
    CreateChatCompletionResponseChoicesInnerMessageFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerMessageToJSON,
    CreateChatCompletionResponseChoicesInnerMessageToJSONTyped,
} from './CreateChatCompletionResponseChoicesInnerMessage';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInner
 */
export interface CreateChatCompletionResponseChoicesInner {
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerFinishReasonEnum}
     * @memberof CreateChatCompletionResponseChoicesInner
     */
    finish_reason: CreateChatCompletionResponseChoicesInnerFinishReasonEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseChoicesInner
     */
    index: number;
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerMessage}
     * @memberof CreateChatCompletionResponseChoicesInner
     */
    message: CreateChatCompletionResponseChoicesInnerMessage;
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerLogprobs}
     * @memberof CreateChatCompletionResponseChoicesInner
     */
    logprobs: CreateChatCompletionResponseChoicesInnerLogprobs;
}


/**
 * @export
 */
export const CreateChatCompletionResponseChoicesInnerFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length',
    ToolCalls: 'tool_calls',
    ContentFilter: 'content_filter',
    FunctionCall: 'function_call'
} as const;
export type CreateChatCompletionResponseChoicesInnerFinishReasonEnum = typeof CreateChatCompletionResponseChoicesInnerFinishReasonEnum[keyof typeof CreateChatCompletionResponseChoicesInnerFinishReasonEnum];


/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInner interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInner(value: object): value is CreateChatCompletionResponseChoicesInner {
    if (!('finish_reason' in value) || value['finish_reason'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('logprobs' in value) || value['logprobs'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerFromJSON(json: any): CreateChatCompletionResponseChoicesInner {
    return CreateChatCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'finish_reason': json['finish_reason'],
        'index': json['index'],
        'message': CreateChatCompletionResponseChoicesInnerMessageFromJSON(json['message']),
        'logprobs': CreateChatCompletionResponseChoicesInnerLogprobsFromJSON(json['logprobs']),
    };
}

export function CreateChatCompletionResponseChoicesInnerToJSON(json: any): CreateChatCompletionResponseChoicesInner {
    return CreateChatCompletionResponseChoicesInnerToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerToJSONTyped(value?: CreateChatCompletionResponseChoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'finish_reason': value['finish_reason'],
        'index': value['index'],
        'message': CreateChatCompletionResponseChoicesInnerMessageToJSON(value['message']),
        'logprobs': CreateChatCompletionResponseChoicesInnerLogprobsToJSON(value['logprobs']),
    };
}

