/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation
 */
export interface CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation {
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation
     */
    end_index: number;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation
     */
    start_index: number;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation
     */
    title: string;
}

/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation(value: object): value is CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation {
    if (!('end_index' in value) || value['end_index'] === undefined) return false;
    if (!('start_index' in value) || value['start_index'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSON(json: any): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation {
    return CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation {
    if (json == null) {
        return json;
    }
    return {
        
        'end_index': json['end_index'],
        'start_index': json['start_index'],
        'url': json['url'],
        'title': json['title'],
    };
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSON(json: any): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation {
    return CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSONTyped(value?: CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_index': value['end_index'],
        'start_index': value['start_index'],
        'url': value['url'],
        'title': value['title'],
    };
}

