/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCompletionResponseChoicesInner } from './CreateCompletionResponseChoicesInner';
import {
    CreateCompletionResponseChoicesInnerFromJSON,
    CreateCompletionResponseChoicesInnerFromJSONTyped,
    CreateCompletionResponseChoicesInnerToJSON,
    CreateCompletionResponseChoicesInnerToJSONTyped,
} from './CreateCompletionResponseChoicesInner';
import type { CompletionUsage } from './CompletionUsage';
import {
    CompletionUsageFromJSON,
    CompletionUsageFromJSONTyped,
    CompletionUsageToJSON,
    CompletionUsageToJSONTyped,
} from './CompletionUsage';

/**
 * 
 * @export
 * @interface CreateCompletionResponse
 */
export interface CreateCompletionResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateCompletionResponse
     */
    id: string;
    /**
     * 
     * @type {CreateCompletionResponseObjectEnum}
     * @memberof CreateCompletionResponse
     */
    object: CreateCompletionResponseObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateCompletionResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCompletionResponse
     */
    model: string;
    /**
     * 
     * @type {Array<CreateCompletionResponseChoicesInner>}
     * @memberof CreateCompletionResponse
     */
    choices: Array<CreateCompletionResponseChoicesInner>;
    /**
     * 
     * @type {CompletionUsage}
     * @memberof CreateCompletionResponse
     */
    usage?: CompletionUsage;
    /**
     * 
     * @type {string}
     * @memberof CreateCompletionResponse
     */
    system_fingerprint?: string;
}


/**
 * @export
 */
export const CreateCompletionResponseObjectEnum = {
    TextCompletion: 'text_completion'
} as const;
export type CreateCompletionResponseObjectEnum = typeof CreateCompletionResponseObjectEnum[keyof typeof CreateCompletionResponseObjectEnum];


/**
 * Check if a given object implements the CreateCompletionResponse interface.
 */
export function instanceOfCreateCompletionResponse(value: object): value is CreateCompletionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function CreateCompletionResponseFromJSON(json: any): CreateCompletionResponse {
    return CreateCompletionResponseFromJSONTyped(json, false);
}

export function CreateCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(CreateCompletionResponseChoicesInnerFromJSON)),
        'usage': json['usage'] == null ? undefined : CompletionUsageFromJSON(json['usage']),
        'system_fingerprint': json['system_fingerprint'] == null ? undefined : json['system_fingerprint'],
    };
}

export function CreateCompletionResponseToJSON(json: any): CreateCompletionResponse {
    return CreateCompletionResponseToJSONTyped(json, false);
}

export function CreateCompletionResponseToJSONTyped(value?: CreateCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(CreateCompletionResponseChoicesInnerToJSON)),
        'usage': CompletionUsageToJSON(value['usage']),
        'system_fingerprint': value['system_fingerprint'],
    };
}

