/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseResponseOutputInnerAnyOfContentInner } from './CreateResponseResponseOutputInnerAnyOfContentInner';
import {
    CreateResponseResponseOutputInnerAnyOfContentInnerFromJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerFromJSONTyped,
    CreateResponseResponseOutputInnerAnyOfContentInnerToJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOfContentInner';
import type { CreateResponseResponseOutputInnerAnyOf1 } from './CreateResponseResponseOutputInnerAnyOf1';
import {
    CreateResponseResponseOutputInnerAnyOf1FromJSON,
    CreateResponseResponseOutputInnerAnyOf1FromJSONTyped,
    CreateResponseResponseOutputInnerAnyOf1ToJSON,
    CreateResponseResponseOutputInnerAnyOf1ToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOf1';
import type { CreateResponseResponseOutputInnerAnyOf2 } from './CreateResponseResponseOutputInnerAnyOf2';
import {
    CreateResponseResponseOutputInnerAnyOf2FromJSON,
    CreateResponseResponseOutputInnerAnyOf2FromJSONTyped,
    CreateResponseResponseOutputInnerAnyOf2ToJSON,
    CreateResponseResponseOutputInnerAnyOf2ToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOf2';
import type { CreateResponseResponseOutputInnerAnyOf } from './CreateResponseResponseOutputInnerAnyOf';
import {
    CreateResponseResponseOutputInnerAnyOfFromJSON,
    CreateResponseResponseOutputInnerAnyOfFromJSONTyped,
    CreateResponseResponseOutputInnerAnyOfToJSON,
    CreateResponseResponseOutputInnerAnyOfToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOf';

/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInner
 */
export interface CreateResponseResponseOutputInner {
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInner
     */
    id: string;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerTypeEnum}
     * @memberof CreateResponseResponseOutputInner
     */
    type: CreateResponseResponseOutputInnerTypeEnum;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerRoleEnum}
     * @memberof CreateResponseResponseOutputInner
     */
    role: CreateResponseResponseOutputInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInner
     */
    status: string;
    /**
     * 
     * @type {Array<CreateResponseResponseOutputInnerAnyOfContentInner>}
     * @memberof CreateResponseResponseOutputInner
     */
    content: Array<CreateResponseResponseOutputInnerAnyOfContentInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInner
     */
    call_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInner
     */
    arguments: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreateResponseResponseOutputInner
     */
    summary?: Array<{ [key: string]: any; }>;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerTypeEnum = {
    Message: 'message',
    FunctionCall: 'function_call',
    Reasoning: 'reasoning'
} as const;
export type CreateResponseResponseOutputInnerTypeEnum = typeof CreateResponseResponseOutputInnerTypeEnum[keyof typeof CreateResponseResponseOutputInnerTypeEnum];

/**
 * @export
 */
export const CreateResponseResponseOutputInnerRoleEnum = {
    Assistant: 'assistant'
} as const;
export type CreateResponseResponseOutputInnerRoleEnum = typeof CreateResponseResponseOutputInnerRoleEnum[keyof typeof CreateResponseResponseOutputInnerRoleEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInner interface.
 */
export function instanceOfCreateResponseResponseOutputInner(value: object): value is CreateResponseResponseOutputInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('call_id' in value) || value['call_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('arguments' in value) || value['arguments'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerFromJSON(json: any): CreateResponseResponseOutputInner {
    return CreateResponseResponseOutputInnerFromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'role': json['role'],
        'status': json['status'],
        'content': ((json['content'] as Array<any>).map(CreateResponseResponseOutputInnerAnyOfContentInnerFromJSON)),
        'call_id': json['call_id'],
        'name': json['name'],
        'arguments': json['arguments'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function CreateResponseResponseOutputInnerToJSON(json: any): CreateResponseResponseOutputInner {
    return CreateResponseResponseOutputInnerToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerToJSONTyped(value?: CreateResponseResponseOutputInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'role': value['role'],
        'status': value['status'],
        'content': ((value['content'] as Array<any>).map(CreateResponseResponseOutputInnerAnyOfContentInnerToJSON)),
        'call_id': value['call_id'],
        'name': value['name'],
        'arguments': value['arguments'],
        'summary': value['summary'],
    };
}

