/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner } from './CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner';
import {
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSON,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSON,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSONTyped,
} from './CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner';
import type { ChatCompletionMessageAnyOf3ToolCallsInner } from './ChatCompletionMessageAnyOf3ToolCallsInner';
import {
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerFromJSONTyped,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSON,
    ChatCompletionMessageAnyOf3ToolCallsInnerToJSONTyped,
} from './ChatCompletionMessageAnyOf3ToolCallsInner';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInnerMessage
 */
export interface CreateChatCompletionResponseChoicesInnerMessage {
    [key: string]: any | any;
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerMessageRoleEnum}
     * @memberof CreateChatCompletionResponseChoicesInnerMessage
     */
    role: CreateChatCompletionResponseChoicesInnerMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponseChoicesInnerMessage
     */
    content: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponseChoicesInnerMessage
     */
    refusal?: string | null;
    /**
     * 
     * @type {Array<ChatCompletionMessageAnyOf3ToolCallsInner>}
     * @memberof CreateChatCompletionResponseChoicesInnerMessage
     */
    tool_calls?: Array<ChatCompletionMessageAnyOf3ToolCallsInner>;
    /**
     * 
     * @type {Array<CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner>}
     * @memberof CreateChatCompletionResponseChoicesInnerMessage
     */
    annotations?: Array<CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner>;
}


/**
 * @export
 */
export const CreateChatCompletionResponseChoicesInnerMessageRoleEnum = {
    Assistant: 'assistant'
} as const;
export type CreateChatCompletionResponseChoicesInnerMessageRoleEnum = typeof CreateChatCompletionResponseChoicesInnerMessageRoleEnum[keyof typeof CreateChatCompletionResponseChoicesInnerMessageRoleEnum];


/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInnerMessage interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInnerMessage(value: object): value is CreateChatCompletionResponseChoicesInnerMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerMessageFromJSON(json: any): CreateChatCompletionResponseChoicesInnerMessage {
    return CreateChatCompletionResponseChoicesInnerMessageFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInnerMessage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'role': json['role'],
        'content': json['content'],
        'refusal': json['refusal'] == null ? undefined : json['refusal'],
        'tool_calls': json['tool_calls'] == null ? undefined : ((json['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerFromJSON)),
        'annotations': json['annotations'] == null ? undefined : ((json['annotations'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSON)),
    };
}

export function CreateChatCompletionResponseChoicesInnerMessageToJSON(json: any): CreateChatCompletionResponseChoicesInnerMessage {
    return CreateChatCompletionResponseChoicesInnerMessageToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageToJSONTyped(value?: CreateChatCompletionResponseChoicesInnerMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'role': value['role'],
        'content': value['content'],
        'refusal': value['refusal'],
        'tool_calls': value['tool_calls'] == null ? undefined : ((value['tool_calls'] as Array<any>).map(ChatCompletionMessageAnyOf3ToolCallsInnerToJSON)),
        'annotations': value['annotations'] == null ? undefined : ((value['annotations'] as Array<any>).map(CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSON)),
    };
}

