/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema
 */
export interface CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema
     */
    schema?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema
     */
    strict?: boolean | null;
}

/**
 * Check if a given object implements the CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema interface.
 */
export function instanceOfCreateChatCompletionRequestResponseFormatAnyOf2JsonSchema(value: object): value is CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema {
    return CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSON(json: any): CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema {
    return CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSONTyped(value?: CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'description': value['description'],
        'schema': value['schema'],
        'strict': value['strict'],
    };
}

