/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestToolChoiceAnyOfFunction } from './CreateChatCompletionRequestToolChoiceAnyOfFunction';
import {
    CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSON,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSONTyped,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSON,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSONTyped,
} from './CreateChatCompletionRequestToolChoiceAnyOfFunction';

/**
 * 
 * @export
 * @interface CreateChatCompletionRequestToolChoiceAnyOf
 */
export interface CreateChatCompletionRequestToolChoiceAnyOf {
    /**
     * 
     * @type {CreateChatCompletionRequestToolChoiceAnyOfTypeEnum}
     * @memberof CreateChatCompletionRequestToolChoiceAnyOf
     */
    type: CreateChatCompletionRequestToolChoiceAnyOfTypeEnum;
    /**
     * 
     * @type {CreateChatCompletionRequestToolChoiceAnyOfFunction}
     * @memberof CreateChatCompletionRequestToolChoiceAnyOf
     */
    _function: CreateChatCompletionRequestToolChoiceAnyOfFunction;
}


/**
 * @export
 */
export const CreateChatCompletionRequestToolChoiceAnyOfTypeEnum = {
    Function: 'function'
} as const;
export type CreateChatCompletionRequestToolChoiceAnyOfTypeEnum = typeof CreateChatCompletionRequestToolChoiceAnyOfTypeEnum[keyof typeof CreateChatCompletionRequestToolChoiceAnyOfTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestToolChoiceAnyOf interface.
 */
export function instanceOfCreateChatCompletionRequestToolChoiceAnyOf(value: object): value is CreateChatCompletionRequestToolChoiceAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestToolChoiceAnyOfFromJSON(json: any): CreateChatCompletionRequestToolChoiceAnyOf {
    return CreateChatCompletionRequestToolChoiceAnyOfFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestToolChoiceAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSON(json['function']),
    };
}

export function CreateChatCompletionRequestToolChoiceAnyOfToJSON(json: any): CreateChatCompletionRequestToolChoiceAnyOf {
    return CreateChatCompletionRequestToolChoiceAnyOfToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceAnyOfToJSONTyped(value?: CreateChatCompletionRequestToolChoiceAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSON(value['_function']),
    };
}

