/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestStreamOptions
 */
export interface CreateChatCompletionRequestStreamOptions {
    /**
     * 
     * @type {boolean}
     * @memberof CreateChatCompletionRequestStreamOptions
     */
    include_usage?: boolean;
}

/**
 * Check if a given object implements the CreateChatCompletionRequestStreamOptions interface.
 */
export function instanceOfCreateChatCompletionRequestStreamOptions(value: object): value is CreateChatCompletionRequestStreamOptions {
    return true;
}

export function CreateChatCompletionRequestStreamOptionsFromJSON(json: any): CreateChatCompletionRequestStreamOptions {
    return CreateChatCompletionRequestStreamOptionsFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestStreamOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestStreamOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'include_usage': json['include_usage'] == null ? undefined : json['include_usage'],
    };
}

export function CreateChatCompletionRequestStreamOptionsToJSON(json: any): CreateChatCompletionRequestStreamOptions {
    return CreateChatCompletionRequestStreamOptionsToJSONTyped(json, false);
}

export function CreateChatCompletionRequestStreamOptionsToJSONTyped(value?: CreateChatCompletionRequestStreamOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'include_usage': value['include_usage'],
    };
}

