/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf } from './CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf';
import {
    CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfFromJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfFromJSONTyped,
    CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfToJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerAnyOfToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOfContentInnerAnyOf';
import type { ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf } from './ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf';
import {
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfFromJSONTyped,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSON,
    ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOfToJSONTyped,
} from './ChatCompletionMessageAnyOf3ContentAnyOfInnerAnyOf';

/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInnerAnyOfContentInner
 */
export interface CreateResponseResponseOutputInnerAnyOfContentInner {
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInner
     */
    type: CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInner
     */
    text: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInner
     */
    annotations?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOfContentInner
     */
    refusal: string;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum = {
    OutputText: 'output_text',
    Refusal: 'refusal'
} as const;
export type CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum = typeof CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum[keyof typeof CreateResponseResponseOutputInnerAnyOfContentInnerTypeEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInnerAnyOfContentInner interface.
 */
export function instanceOfCreateResponseResponseOutputInnerAnyOfContentInner(value: object): value is CreateResponseResponseOutputInnerAnyOfContentInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerFromJSON(json: any): CreateResponseResponseOutputInnerAnyOfContentInner {
    return CreateResponseResponseOutputInnerAnyOfContentInnerFromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInnerAnyOfContentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
        'refusal': json['refusal'],
    };
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerToJSON(json: any): CreateResponseResponseOutputInnerAnyOfContentInner {
    return CreateResponseResponseOutputInnerAnyOfContentInnerToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfContentInnerToJSONTyped(value?: CreateResponseResponseOutputInnerAnyOfContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'annotations': value['annotations'],
        'refusal': value['refusal'],
    };
}

