/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseUsage } from './ResponseUsage';
import {
    ResponseUsageFromJSON,
    ResponseUsageFromJSONTyped,
    ResponseUsageToJSON,
    ResponseUsageToJSONTyped,
} from './ResponseUsage';
import type { CreateResponseResponseToolChoice } from './CreateResponseResponseToolChoice';
import {
    CreateResponseResponseToolChoiceFromJSON,
    CreateResponseResponseToolChoiceFromJSONTyped,
    CreateResponseResponseToolChoiceToJSON,
    CreateResponseResponseToolChoiceToJSONTyped,
} from './CreateResponseResponseToolChoice';
import type { CreateResponseResponseError } from './CreateResponseResponseError';
import {
    CreateResponseResponseErrorFromJSON,
    CreateResponseResponseErrorFromJSONTyped,
    CreateResponseResponseErrorToJSON,
    CreateResponseResponseErrorToJSONTyped,
} from './CreateResponseResponseError';
import type { CreateResponseResponseOutputInner } from './CreateResponseResponseOutputInner';
import {
    CreateResponseResponseOutputInnerFromJSON,
    CreateResponseResponseOutputInnerFromJSONTyped,
    CreateResponseResponseOutputInnerToJSON,
    CreateResponseResponseOutputInnerToJSONTyped,
} from './CreateResponseResponseOutputInner';
import type { CreateResponseResponseIncompleteDetails } from './CreateResponseResponseIncompleteDetails';
import {
    CreateResponseResponseIncompleteDetailsFromJSON,
    CreateResponseResponseIncompleteDetailsFromJSONTyped,
    CreateResponseResponseIncompleteDetailsToJSON,
    CreateResponseResponseIncompleteDetailsToJSONTyped,
} from './CreateResponseResponseIncompleteDetails';
import type { CreateResponseResponseReasoning } from './CreateResponseResponseReasoning';
import {
    CreateResponseResponseReasoningFromJSON,
    CreateResponseResponseReasoningFromJSONTyped,
    CreateResponseResponseReasoningToJSON,
    CreateResponseResponseReasoningToJSONTyped,
} from './CreateResponseResponseReasoning';

/**
 * 
 * @export
 * @interface CreateResponseResponse
 */
export interface CreateResponseResponse {
    [key: string]: any | any;
    /**
     * Unique identifier for this response.
     * @type {string}
     * @memberof CreateResponseResponse
     */
    id: string;
    /**
     * The object type — always "response".
     * @type {CreateResponseResponseObjectEnum}
     * @memberof CreateResponseResponse
     */
    object: CreateResponseResponseObjectEnum;
    /**
     * The status of the response generation.
     * @type {CreateResponseResponseStatusEnum}
     * @memberof CreateResponseResponse
     */
    status: CreateResponseResponseStatusEnum;
    /**
     * Unix timestamp (in seconds) of when this response was created.
     * @type {number}
     * @memberof CreateResponseResponse
     */
    created_at: number;
    /**
     * Unix timestamp of completion. Only present when status is completed.
     * @type {number}
     * @memberof CreateResponseResponse
     */
    completed_at?: number | null;
    /**
     * The model used to generate the response.
     * @type {string}
     * @memberof CreateResponseResponse
     */
    model: string;
    /**
     * An array of content items generated by the model.
     * @type {Array<CreateResponseResponseOutputInner>}
     * @memberof CreateResponseResponse
     */
    output: Array<CreateResponseResponseOutputInner>;
    /**
     * 
     * @type {CreateResponseResponseError}
     * @memberof CreateResponseResponse
     */
    error?: CreateResponseResponseError;
    /**
     * 
     * @type {CreateResponseResponseIncompleteDetails}
     * @memberof CreateResponseResponse
     */
    incomplete_details?: CreateResponseResponseIncompleteDetails;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponse
     */
    instructions?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateResponseResponse
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof CreateResponseResponse
     */
    temperature?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateResponseResponse
     */
    top_p?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateResponseResponse
     */
    max_output_tokens?: number | null;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreateResponseResponse
     */
    tools?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {CreateResponseResponseToolChoice}
     * @memberof CreateResponseResponse
     */
    tool_choice?: CreateResponseResponseToolChoice;
    /**
     * 
     * @type {boolean}
     * @memberof CreateResponseResponse
     */
    parallel_tool_calls?: boolean;
    /**
     * 
     * @type {CreateResponseResponseTruncationEnum}
     * @memberof CreateResponseResponse
     */
    truncation?: CreateResponseResponseTruncationEnum | null;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponse
     */
    previous_response_id?: string | null;
    /**
     * 
     * @type {CreateResponseResponseReasoning}
     * @memberof CreateResponseResponse
     */
    reasoning?: CreateResponseResponseReasoning;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateResponseResponse
     */
    text?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof CreateResponseResponse
     */
    top_logprobs?: number | null;
    /**
     * Token usage details for this response.
     * @type {ResponseUsage}
     * @memberof CreateResponseResponse
     */
    usage?: ResponseUsage;
}


/**
 * @export
 */
export const CreateResponseResponseObjectEnum = {
    Response: 'response'
} as const;
export type CreateResponseResponseObjectEnum = typeof CreateResponseResponseObjectEnum[keyof typeof CreateResponseResponseObjectEnum];

/**
 * @export
 */
export const CreateResponseResponseStatusEnum = {
    Completed: 'completed',
    Failed: 'failed',
    InProgress: 'in_progress',
    Cancelled: 'cancelled',
    Queued: 'queued',
    Incomplete: 'incomplete'
} as const;
export type CreateResponseResponseStatusEnum = typeof CreateResponseResponseStatusEnum[keyof typeof CreateResponseResponseStatusEnum];

/**
 * @export
 */
export const CreateResponseResponseTruncationEnum = {
    Auto: 'auto',
    Disabled: 'disabled'
} as const;
export type CreateResponseResponseTruncationEnum = typeof CreateResponseResponseTruncationEnum[keyof typeof CreateResponseResponseTruncationEnum];


/**
 * Check if a given object implements the CreateResponseResponse interface.
 */
export function instanceOfCreateResponseResponse(value: object): value is CreateResponseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function CreateResponseResponseFromJSON(json: any): CreateResponseResponse {
    return CreateResponseResponseFromJSONTyped(json, false);
}

export function CreateResponseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'object': json['object'],
        'status': json['status'],
        'created_at': json['created_at'],
        'completed_at': json['completed_at'] == null ? undefined : json['completed_at'],
        'model': json['model'],
        'output': ((json['output'] as Array<any>).map(CreateResponseResponseOutputInnerFromJSON)),
        'error': json['error'] == null ? undefined : CreateResponseResponseErrorFromJSON(json['error']),
        'incomplete_details': json['incomplete_details'] == null ? undefined : CreateResponseResponseIncompleteDetailsFromJSON(json['incomplete_details']),
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'top_p': json['top_p'] == null ? undefined : json['top_p'],
        'max_output_tokens': json['max_output_tokens'] == null ? undefined : json['max_output_tokens'],
        'tools': json['tools'] == null ? undefined : json['tools'],
        'tool_choice': json['tool_choice'] == null ? undefined : CreateResponseResponseToolChoiceFromJSON(json['tool_choice']),
        'parallel_tool_calls': json['parallel_tool_calls'] == null ? undefined : json['parallel_tool_calls'],
        'truncation': json['truncation'] == null ? undefined : json['truncation'],
        'previous_response_id': json['previous_response_id'] == null ? undefined : json['previous_response_id'],
        'reasoning': json['reasoning'] == null ? undefined : CreateResponseResponseReasoningFromJSON(json['reasoning']),
        'text': json['text'] == null ? undefined : json['text'],
        'top_logprobs': json['top_logprobs'] == null ? undefined : json['top_logprobs'],
        'usage': json['usage'] == null ? undefined : ResponseUsageFromJSON(json['usage']),
    };
}

export function CreateResponseResponseToJSON(json: any): CreateResponseResponse {
    return CreateResponseResponseToJSONTyped(json, false);
}

export function CreateResponseResponseToJSONTyped(value?: CreateResponseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'object': value['object'],
        'status': value['status'],
        'created_at': value['created_at'],
        'completed_at': value['completed_at'],
        'model': value['model'],
        'output': ((value['output'] as Array<any>).map(CreateResponseResponseOutputInnerToJSON)),
        'error': CreateResponseResponseErrorToJSON(value['error']),
        'incomplete_details': CreateResponseResponseIncompleteDetailsToJSON(value['incomplete_details']),
        'instructions': value['instructions'],
        'metadata': value['metadata'],
        'temperature': value['temperature'],
        'top_p': value['top_p'],
        'max_output_tokens': value['max_output_tokens'],
        'tools': value['tools'],
        'tool_choice': CreateResponseResponseToolChoiceToJSON(value['tool_choice']),
        'parallel_tool_calls': value['parallel_tool_calls'],
        'truncation': value['truncation'],
        'previous_response_id': value['previous_response_id'],
        'reasoning': CreateResponseResponseReasoningToJSON(value['reasoning']),
        'text': value['text'],
        'top_logprobs': value['top_logprobs'],
        'usage': ResponseUsageToJSON(value['usage']),
    };
}

