/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseResponseToolChoice
 */
export interface CreateResponseResponseToolChoice {
}

/**
 * Check if a given object implements the CreateResponseResponseToolChoice interface.
 */
export function instanceOfCreateResponseResponseToolChoice(value: object): value is CreateResponseResponseToolChoice {
    return true;
}

export function CreateResponseResponseToolChoiceFromJSON(json: any): CreateResponseResponseToolChoice {
    return CreateResponseResponseToolChoiceFromJSONTyped(json, false);
}

export function CreateResponseResponseToolChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseToolChoice {
    return json;
}

export function CreateResponseResponseToolChoiceToJSON(json: any): CreateResponseResponseToolChoice {
    return CreateResponseResponseToolChoiceToJSONTyped(json, false);
}

export function CreateResponseResponseToolChoiceToJSONTyped(value?: CreateResponseResponseToolChoice | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

