/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseResponseOutputInnerAnyOfContentInner } from './CreateResponseResponseOutputInnerAnyOfContentInner';
import {
    CreateResponseResponseOutputInnerAnyOfContentInnerFromJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerFromJSONTyped,
    CreateResponseResponseOutputInnerAnyOfContentInnerToJSON,
    CreateResponseResponseOutputInnerAnyOfContentInnerToJSONTyped,
} from './CreateResponseResponseOutputInnerAnyOfContentInner';

/**
 * 
 * @export
 * @interface CreateResponseResponseOutputInnerAnyOf
 */
export interface CreateResponseResponseOutputInnerAnyOf {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateResponseResponseOutputInnerAnyOf
     */
    id: string;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOfTypeEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOf
     */
    type: CreateResponseResponseOutputInnerAnyOfTypeEnum;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOfRoleEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOf
     */
    role: CreateResponseResponseOutputInnerAnyOfRoleEnum;
    /**
     * 
     * @type {CreateResponseResponseOutputInnerAnyOfStatusEnum}
     * @memberof CreateResponseResponseOutputInnerAnyOf
     */
    status: CreateResponseResponseOutputInnerAnyOfStatusEnum;
    /**
     * 
     * @type {Array<CreateResponseResponseOutputInnerAnyOfContentInner>}
     * @memberof CreateResponseResponseOutputInnerAnyOf
     */
    content: Array<CreateResponseResponseOutputInnerAnyOfContentInner>;
}


/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOfTypeEnum = {
    Message: 'message'
} as const;
export type CreateResponseResponseOutputInnerAnyOfTypeEnum = typeof CreateResponseResponseOutputInnerAnyOfTypeEnum[keyof typeof CreateResponseResponseOutputInnerAnyOfTypeEnum];

/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOfRoleEnum = {
    Assistant: 'assistant'
} as const;
export type CreateResponseResponseOutputInnerAnyOfRoleEnum = typeof CreateResponseResponseOutputInnerAnyOfRoleEnum[keyof typeof CreateResponseResponseOutputInnerAnyOfRoleEnum];

/**
 * @export
 */
export const CreateResponseResponseOutputInnerAnyOfStatusEnum = {
    InProgress: 'in_progress',
    Completed: 'completed',
    Incomplete: 'incomplete'
} as const;
export type CreateResponseResponseOutputInnerAnyOfStatusEnum = typeof CreateResponseResponseOutputInnerAnyOfStatusEnum[keyof typeof CreateResponseResponseOutputInnerAnyOfStatusEnum];


/**
 * Check if a given object implements the CreateResponseResponseOutputInnerAnyOf interface.
 */
export function instanceOfCreateResponseResponseOutputInnerAnyOf(value: object): value is CreateResponseResponseOutputInnerAnyOf {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateResponseResponseOutputInnerAnyOfFromJSON(json: any): CreateResponseResponseOutputInnerAnyOf {
    return CreateResponseResponseOutputInnerAnyOfFromJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseOutputInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': json['type'],
        'role': json['role'],
        'status': json['status'],
        'content': ((json['content'] as Array<any>).map(CreateResponseResponseOutputInnerAnyOfContentInnerFromJSON)),
    };
}

export function CreateResponseResponseOutputInnerAnyOfToJSON(json: any): CreateResponseResponseOutputInnerAnyOf {
    return CreateResponseResponseOutputInnerAnyOfToJSONTyped(json, false);
}

export function CreateResponseResponseOutputInnerAnyOfToJSONTyped(value?: CreateResponseResponseOutputInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'type': value['type'],
        'role': value['role'],
        'status': value['status'],
        'content': ((value['content'] as Array<any>).map(CreateResponseResponseOutputInnerAnyOfContentInnerToJSON)),
    };
}

