/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Up to 4 sequences where the API will stop generating further tokens.
 * @export
 * @interface CreateResponseRequestStop
 */
export interface CreateResponseRequestStop {
}

/**
 * Check if a given object implements the CreateResponseRequestStop interface.
 */
export function instanceOfCreateResponseRequestStop(value: object): value is CreateResponseRequestStop {
    return true;
}

export function CreateResponseRequestStopFromJSON(json: any): CreateResponseRequestStop {
    return CreateResponseRequestStopFromJSONTyped(json, false);
}

export function CreateResponseRequestStopFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestStop {
    return json;
}

export function CreateResponseRequestStopToJSON(json: any): CreateResponseRequestStop {
    return CreateResponseRequestStopToJSONTyped(json, false);
}

export function CreateResponseRequestStopToJSONTyped(value?: CreateResponseRequestStop | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

