/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation } from './CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation';
import {
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSON,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSONTyped,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSON,
    CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSONTyped,
} from './CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner
 */
export interface CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner {
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner
     */
    type: CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum;
    /**
     * 
     * @type {CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation}
     * @memberof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner
     */
    url_citation: CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitation;
}


/**
 * @export
 */
export const CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum = {
    UrlCitation: 'url_citation'
} as const;
export type CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum = typeof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum[keyof typeof CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner interface.
 */
export function instanceOfCreateChatCompletionResponseChoicesInnerMessageAnnotationsInner(value: object): value is CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url_citation' in value) || value['url_citation'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSON(json: any): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner {
    return CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url_citation': CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationFromJSON(json['url_citation']),
    };
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSON(json: any): CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner {
    return CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSONTyped(json, false);
}

export function CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerToJSONTyped(value?: CreateChatCompletionResponseChoicesInnerMessageAnnotationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'url_citation': CreateChatCompletionResponseChoicesInnerMessageAnnotationsInnerUrlCitationToJSON(value['url_citation']),
    };
}

