/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateResponseRequestStop } from './CreateResponseRequestStop';
import {
    CreateResponseRequestStopFromJSON,
    CreateResponseRequestStopFromJSONTyped,
    CreateResponseRequestStopToJSON,
    CreateResponseRequestStopToJSONTyped,
} from './CreateResponseRequestStop';
import type { ResponseInput } from './ResponseInput';
import {
    ResponseInputFromJSON,
    ResponseInputFromJSONTyped,
    ResponseInputToJSON,
    ResponseInputToJSONTyped,
} from './ResponseInput';
import type { CreateResponseRequestToolChoice } from './CreateResponseRequestToolChoice';
import {
    CreateResponseRequestToolChoiceFromJSON,
    CreateResponseRequestToolChoiceFromJSONTyped,
    CreateResponseRequestToolChoiceToJSON,
    CreateResponseRequestToolChoiceToJSONTyped,
} from './CreateResponseRequestToolChoice';
import type { CreateResponseRequestText } from './CreateResponseRequestText';
import {
    CreateResponseRequestTextFromJSON,
    CreateResponseRequestTextFromJSONTyped,
    CreateResponseRequestTextToJSON,
    CreateResponseRequestTextToJSONTyped,
} from './CreateResponseRequestText';
import type { CreateResponseRequestReasoning } from './CreateResponseRequestReasoning';
import {
    CreateResponseRequestReasoningFromJSON,
    CreateResponseRequestReasoningFromJSONTyped,
    CreateResponseRequestReasoningToJSON,
    CreateResponseRequestReasoningToJSONTyped,
} from './CreateResponseRequestReasoning';
import type { CreateResponseRequestToolsInner } from './CreateResponseRequestToolsInner';
import {
    CreateResponseRequestToolsInnerFromJSON,
    CreateResponseRequestToolsInnerFromJSONTyped,
    CreateResponseRequestToolsInnerToJSON,
    CreateResponseRequestToolsInnerToJSONTyped,
} from './CreateResponseRequestToolsInner';

/**
 * 
 * @export
 * @interface CreateResponseRequest
 */
export interface CreateResponseRequest {
    [key: string]: any | any;
    /**
     * ID of the model to use for this response.
     * @type {string}
     * @memberof CreateResponseRequest
     */
    model: string;
    /**
     * Text, image, or file inputs to the model. Can be a string or an array of input items.
     * @type {ResponseInput}
     * @memberof CreateResponseRequest
     */
    input: ResponseInput;
    /**
     * A system (or developer) message inserted into the model's context.
     * @type {string}
     * @memberof CreateResponseRequest
     */
    instructions?: string | null;
    /**
     * If true, response data will be streamed as server-sent events.
     * @type {boolean}
     * @memberof CreateResponseRequest
     */
    stream?: boolean | null;
    /**
     * Sampling temperature between 0 and 2. Higher values make output more random.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    temperature?: number | null;
    /**
     * Nucleus sampling: consider tokens with top_p probability mass.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    top_p?: number | null;
    /**
     * Upper bound for tokens that can be generated, including visible output and reasoning tokens.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    max_output_tokens?: number | null;
    /**
     * An array of function tools the model may call while generating a response.
     * @type {Array<CreateResponseRequestToolsInner>}
     * @memberof CreateResponseRequest
     */
    tools?: Array<CreateResponseRequestToolsInner>;
    /**
     * 
     * @type {CreateResponseRequestToolChoice}
     * @memberof CreateResponseRequest
     */
    tool_choice?: CreateResponseRequestToolChoice;
    /**
     * Whether to allow the model to run tool calls in parallel.
     * @type {boolean}
     * @memberof CreateResponseRequest
     */
    parallel_tool_calls?: boolean | null;
    /**
     * 
     * @type {CreateResponseRequestReasoning}
     * @memberof CreateResponseRequest
     */
    reasoning?: CreateResponseRequestReasoning;
    /**
     * "auto" truncates input to fit context window. "disabled" (default) returns 400 if input exceeds context.
     * @type {CreateResponseRequestTruncationEnum}
     * @memberof CreateResponseRequest
     */
    truncation?: CreateResponseRequestTruncationEnum | null;
    /**
     * ID of a previous response to continue a multi-turn conversation.
     * @type {string}
     * @memberof CreateResponseRequest
     */
    previous_response_id?: string | null;
    /**
     * Whether to store the response for later retrieval via API.
     * @type {boolean}
     * @memberof CreateResponseRequest
     */
    store?: boolean | null;
    /**
     * Set of key-value pairs for additional information.
     * @type {{ [key: string]: string; }}
     * @memberof CreateResponseRequest
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {CreateResponseRequestText}
     * @memberof CreateResponseRequest
     */
    text?: CreateResponseRequestText;
    /**
     * Number of most likely tokens to return at each position (0-20).
     * @type {number}
     * @memberof CreateResponseRequest
     */
    top_logprobs?: number | null;
    /**
     * If specified, the system will attempt deterministic sampling.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    seed?: number | null;
    /**
     * 
     * @type {CreateResponseRequestStop}
     * @memberof CreateResponseRequest
     */
    stop?: CreateResponseRequestStop | null;
    /**
     * Number of highest probability tokens to keep for top-k sampling. -1 to disable.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    top_k?: number | null;
    /**
     * Penalizes new tokens based on whether they appear in the generated text so far. Values > 1.0 penalize repetitions.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    repetition_penalty?: number | null;
    /**
     * Minimum number of tokens to generate before allowing a stop condition.
     * @type {number}
     * @memberof CreateResponseRequest
     */
    min_tokens?: number;
}


/**
 * @export
 */
export const CreateResponseRequestTruncationEnum = {
    Auto: 'auto',
    Disabled: 'disabled'
} as const;
export type CreateResponseRequestTruncationEnum = typeof CreateResponseRequestTruncationEnum[keyof typeof CreateResponseRequestTruncationEnum];


/**
 * Check if a given object implements the CreateResponseRequest interface.
 */
export function instanceOfCreateResponseRequest(value: object): value is CreateResponseRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function CreateResponseRequestFromJSON(json: any): CreateResponseRequest {
    return CreateResponseRequestFromJSONTyped(json, false);
}

export function CreateResponseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'model': json['model'],
        'input': ResponseInputFromJSON(json['input']),
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'top_p': json['top_p'] == null ? undefined : json['top_p'],
        'max_output_tokens': json['max_output_tokens'] == null ? undefined : json['max_output_tokens'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(CreateResponseRequestToolsInnerFromJSON)),
        'tool_choice': json['tool_choice'] == null ? undefined : CreateResponseRequestToolChoiceFromJSON(json['tool_choice']),
        'parallel_tool_calls': json['parallel_tool_calls'] == null ? undefined : json['parallel_tool_calls'],
        'reasoning': json['reasoning'] == null ? undefined : CreateResponseRequestReasoningFromJSON(json['reasoning']),
        'truncation': json['truncation'] == null ? undefined : json['truncation'],
        'previous_response_id': json['previous_response_id'] == null ? undefined : json['previous_response_id'],
        'store': json['store'] == null ? undefined : json['store'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'text': json['text'] == null ? undefined : CreateResponseRequestTextFromJSON(json['text']),
        'top_logprobs': json['top_logprobs'] == null ? undefined : json['top_logprobs'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'stop': json['stop'] == null ? undefined : CreateResponseRequestStopFromJSON(json['stop']),
        'top_k': json['top_k'] == null ? undefined : json['top_k'],
        'repetition_penalty': json['repetition_penalty'] == null ? undefined : json['repetition_penalty'],
        'min_tokens': json['min_tokens'] == null ? undefined : json['min_tokens'],
    };
}

export function CreateResponseRequestToJSON(json: any): CreateResponseRequest {
    return CreateResponseRequestToJSONTyped(json, false);
}

export function CreateResponseRequestToJSONTyped(value?: CreateResponseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'model': value['model'],
        'input': ResponseInputToJSON(value['input']),
        'instructions': value['instructions'],
        'stream': value['stream'],
        'temperature': value['temperature'],
        'top_p': value['top_p'],
        'max_output_tokens': value['max_output_tokens'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(CreateResponseRequestToolsInnerToJSON)),
        'tool_choice': CreateResponseRequestToolChoiceToJSON(value['tool_choice']),
        'parallel_tool_calls': value['parallel_tool_calls'],
        'reasoning': CreateResponseRequestReasoningToJSON(value['reasoning']),
        'truncation': value['truncation'],
        'previous_response_id': value['previous_response_id'],
        'store': value['store'],
        'metadata': value['metadata'],
        'text': CreateResponseRequestTextToJSON(value['text']),
        'top_logprobs': value['top_logprobs'],
        'seed': value['seed'],
        'stop': CreateResponseRequestStopToJSON(value['stop']),
        'top_k': value['top_k'],
        'repetition_penalty': value['repetition_penalty'],
        'min_tokens': value['min_tokens'],
    };
}

