/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCompletionResponseChoicesInnerLogprobs
 */
export interface CreateCompletionResponseChoicesInnerLogprobs {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCompletionResponseChoicesInnerLogprobs
     */
    tokens?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateCompletionResponseChoicesInnerLogprobs
     */
    token_logprobs?: Array<number>;
    /**
     * 
     * @type {Array<{ [key: string]: number; }>}
     * @memberof CreateCompletionResponseChoicesInnerLogprobs
     */
    top_logprobs?: Array<{ [key: string]: number; }>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateCompletionResponseChoicesInnerLogprobs
     */
    text_offset?: Array<number>;
}

/**
 * Check if a given object implements the CreateCompletionResponseChoicesInnerLogprobs interface.
 */
export function instanceOfCreateCompletionResponseChoicesInnerLogprobs(value: object): value is CreateCompletionResponseChoicesInnerLogprobs {
    return true;
}

export function CreateCompletionResponseChoicesInnerLogprobsFromJSON(json: any): CreateCompletionResponseChoicesInnerLogprobs {
    return CreateCompletionResponseChoicesInnerLogprobsFromJSONTyped(json, false);
}

export function CreateCompletionResponseChoicesInnerLogprobsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompletionResponseChoicesInnerLogprobs {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': json['tokens'] == null ? undefined : json['tokens'],
        'token_logprobs': json['token_logprobs'] == null ? undefined : json['token_logprobs'],
        'top_logprobs': json['top_logprobs'] == null ? undefined : json['top_logprobs'],
        'text_offset': json['text_offset'] == null ? undefined : json['text_offset'],
    };
}

export function CreateCompletionResponseChoicesInnerLogprobsToJSON(json: any): CreateCompletionResponseChoicesInnerLogprobs {
    return CreateCompletionResponseChoicesInnerLogprobsToJSONTyped(json, false);
}

export function CreateCompletionResponseChoicesInnerLogprobsToJSONTyped(value?: CreateCompletionResponseChoicesInnerLogprobs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': value['tokens'],
        'token_logprobs': value['token_logprobs'],
        'top_logprobs': value['top_logprobs'],
        'text_offset': value['text_offset'],
    };
}

