/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCompletionResponseChoicesInnerLogprobs } from './CreateCompletionResponseChoicesInnerLogprobs';
import {
    CreateCompletionResponseChoicesInnerLogprobsFromJSON,
    CreateCompletionResponseChoicesInnerLogprobsFromJSONTyped,
    CreateCompletionResponseChoicesInnerLogprobsToJSON,
    CreateCompletionResponseChoicesInnerLogprobsToJSONTyped,
} from './CreateCompletionResponseChoicesInnerLogprobs';

/**
 * 
 * @export
 * @interface CreateCompletionResponseChoicesInner
 */
export interface CreateCompletionResponseChoicesInner {
    /**
     * 
     * @type {string}
     * @memberof CreateCompletionResponseChoicesInner
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCompletionResponseChoicesInner
     */
    index: number;
    /**
     * 
     * @type {CreateCompletionResponseChoicesInnerLogprobs}
     * @memberof CreateCompletionResponseChoicesInner
     */
    logprobs: CreateCompletionResponseChoicesInnerLogprobs;
    /**
     * 
     * @type {CreateCompletionResponseChoicesInnerFinishReasonEnum}
     * @memberof CreateCompletionResponseChoicesInner
     */
    finish_reason: CreateCompletionResponseChoicesInnerFinishReasonEnum | null;
}


/**
 * @export
 */
export const CreateCompletionResponseChoicesInnerFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length'
} as const;
export type CreateCompletionResponseChoicesInnerFinishReasonEnum = typeof CreateCompletionResponseChoicesInnerFinishReasonEnum[keyof typeof CreateCompletionResponseChoicesInnerFinishReasonEnum];


/**
 * Check if a given object implements the CreateCompletionResponseChoicesInner interface.
 */
export function instanceOfCreateCompletionResponseChoicesInner(value: object): value is CreateCompletionResponseChoicesInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('logprobs' in value) || value['logprobs'] === undefined) return false;
    if (!('finish_reason' in value) || value['finish_reason'] === undefined) return false;
    return true;
}

export function CreateCompletionResponseChoicesInnerFromJSON(json: any): CreateCompletionResponseChoicesInner {
    return CreateCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function CreateCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompletionResponseChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'index': json['index'],
        'logprobs': CreateCompletionResponseChoicesInnerLogprobsFromJSON(json['logprobs']),
        'finish_reason': json['finish_reason'],
    };
}

export function CreateCompletionResponseChoicesInnerToJSON(json: any): CreateCompletionResponseChoicesInner {
    return CreateCompletionResponseChoicesInnerToJSONTyped(json, false);
}

export function CreateCompletionResponseChoicesInnerToJSONTyped(value?: CreateCompletionResponseChoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'index': value['index'],
        'logprobs': CreateCompletionResponseChoicesInnerLogprobsToJSON(value['logprobs']),
        'finish_reason': value['finish_reason'],
    };
}

