/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUploadRequest
 */
export interface CreateUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUploadRequest
     */
    filename: string;
    /**
     * 
     * @type {CreateUploadRequestPurposeEnum}
     * @memberof CreateUploadRequest
     */
    purpose: CreateUploadRequestPurposeEnum;
    /**
     * Declared total size in bytes; checked against `purpose` limits
     * @type {number}
     * @memberof CreateUploadRequest
     */
    bytes: number;
    /**
     * Mime type; checked against `purpose` allowlist
     * @type {string}
     * @memberof CreateUploadRequest
     */
    mime_type: string;
}


/**
 * @export
 */
export const CreateUploadRequestPurposeEnum = {
    Vision: 'vision',
    Video: 'video',
    Audio: 'audio',
    Document: 'document'
} as const;
export type CreateUploadRequestPurposeEnum = typeof CreateUploadRequestPurposeEnum[keyof typeof CreateUploadRequestPurposeEnum];


/**
 * Check if a given object implements the CreateUploadRequest interface.
 */
export function instanceOfCreateUploadRequest(value: object): value is CreateUploadRequest {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('mime_type' in value) || value['mime_type'] === undefined) return false;
    return true;
}

export function CreateUploadRequestFromJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestFromJSONTyped(json, false);
}

export function CreateUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'purpose': json['purpose'],
        'bytes': json['bytes'],
        'mime_type': json['mime_type'],
    };
}

export function CreateUploadRequestToJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestToJSONTyped(json, false);
}

export function CreateUploadRequestToJSONTyped(value?: CreateUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'purpose': value['purpose'],
        'bytes': value['bytes'],
        'mime_type': value['mime_type'],
    };
}

