/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for reasoning models: effort level and summary format.
 * @export
 * @interface CreateResponseRequestReasoning
 */
export interface CreateResponseRequestReasoning {
    /**
     * 
     * @type {CreateResponseRequestReasoningEffortEnum}
     * @memberof CreateResponseRequestReasoning
     */
    effort?: CreateResponseRequestReasoningEffortEnum;
    /**
     * 
     * @type {CreateResponseRequestReasoningSummaryEnum}
     * @memberof CreateResponseRequestReasoning
     */
    summary?: CreateResponseRequestReasoningSummaryEnum | null;
}


/**
 * @export
 */
export const CreateResponseRequestReasoningEffortEnum = {
    None: 'none',
    Minimal: 'minimal',
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Xhigh: 'xhigh'
} as const;
export type CreateResponseRequestReasoningEffortEnum = typeof CreateResponseRequestReasoningEffortEnum[keyof typeof CreateResponseRequestReasoningEffortEnum];

/**
 * @export
 */
export const CreateResponseRequestReasoningSummaryEnum = {
    Auto: 'auto',
    Concise: 'concise',
    Detailed: 'detailed'
} as const;
export type CreateResponseRequestReasoningSummaryEnum = typeof CreateResponseRequestReasoningSummaryEnum[keyof typeof CreateResponseRequestReasoningSummaryEnum];


/**
 * Check if a given object implements the CreateResponseRequestReasoning interface.
 */
export function instanceOfCreateResponseRequestReasoning(value: object): value is CreateResponseRequestReasoning {
    return true;
}

export function CreateResponseRequestReasoningFromJSON(json: any): CreateResponseRequestReasoning {
    return CreateResponseRequestReasoningFromJSONTyped(json, false);
}

export function CreateResponseRequestReasoningFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseRequestReasoning {
    if (json == null) {
        return json;
    }
    return {
        
        'effort': json['effort'] == null ? undefined : json['effort'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function CreateResponseRequestReasoningToJSON(json: any): CreateResponseRequestReasoning {
    return CreateResponseRequestReasoningToJSONTyped(json, false);
}

export function CreateResponseRequestReasoningToJSONTyped(value?: CreateResponseRequestReasoning | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'effort': value['effort'],
        'summary': value['summary'],
    };
}

