/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestResponseFormatAnyOf2 } from './CreateChatCompletionRequestResponseFormatAnyOf2';
import {
    CreateChatCompletionRequestResponseFormatAnyOf2FromJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2FromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOf2ToJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2ToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf2';
import type { CreateChatCompletionRequestResponseFormatAnyOf } from './CreateChatCompletionRequestResponseFormatAnyOf';
import {
    CreateChatCompletionRequestResponseFormatAnyOfFromJSON,
    CreateChatCompletionRequestResponseFormatAnyOfFromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOfToJSON,
    CreateChatCompletionRequestResponseFormatAnyOfToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf';
import type { CreateChatCompletionRequestResponseFormatAnyOf1 } from './CreateChatCompletionRequestResponseFormatAnyOf1';
import {
    CreateChatCompletionRequestResponseFormatAnyOf1FromJSON,
    CreateChatCompletionRequestResponseFormatAnyOf1FromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOf1ToJSON,
    CreateChatCompletionRequestResponseFormatAnyOf1ToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf1';
import type { CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema } from './CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema';
import {
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSONTyped,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSON,
    CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSONTyped,
} from './CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema';

/**
 * Output format: { "type": "text" }, { "type": "json_object" }, or { "type": "json_schema", "json_schema": {...} }.
 * @export
 * @interface CreateChatCompletionRequestResponseFormat
 */
export interface CreateChatCompletionRequestResponseFormat {
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatTypeEnum}
     * @memberof CreateChatCompletionRequestResponseFormat
     */
    type: CreateChatCompletionRequestResponseFormatTypeEnum;
    /**
     * 
     * @type {CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema}
     * @memberof CreateChatCompletionRequestResponseFormat
     */
    json_schema: CreateChatCompletionRequestResponseFormatAnyOf2JsonSchema;
}


/**
 * @export
 */
export const CreateChatCompletionRequestResponseFormatTypeEnum = {
    Text: 'text',
    JsonObject: 'json_object',
    JsonSchema: 'json_schema'
} as const;
export type CreateChatCompletionRequestResponseFormatTypeEnum = typeof CreateChatCompletionRequestResponseFormatTypeEnum[keyof typeof CreateChatCompletionRequestResponseFormatTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestResponseFormat interface.
 */
export function instanceOfCreateChatCompletionRequestResponseFormat(value: object): value is CreateChatCompletionRequestResponseFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('json_schema' in value) || value['json_schema'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestResponseFormatFromJSON(json: any): CreateChatCompletionRequestResponseFormat {
    return CreateChatCompletionRequestResponseFormatFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestResponseFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'json_schema': CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaFromJSON(json['json_schema']),
    };
}

export function CreateChatCompletionRequestResponseFormatToJSON(json: any): CreateChatCompletionRequestResponseFormat {
    return CreateChatCompletionRequestResponseFormatToJSONTyped(json, false);
}

export function CreateChatCompletionRequestResponseFormatToJSONTyped(value?: CreateChatCompletionRequestResponseFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'json_schema': CreateChatCompletionRequestResponseFormatAnyOf2JsonSchemaToJSON(value['json_schema']),
    };
}

