/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponseResponseReasoning
 */
export interface CreateResponseResponseReasoning {
    /**
     * 
     * @type {CreateResponseResponseReasoningEffortEnum}
     * @memberof CreateResponseResponseReasoning
     */
    effort?: CreateResponseResponseReasoningEffortEnum;
    /**
     * 
     * @type {CreateResponseResponseReasoningSummaryEnum}
     * @memberof CreateResponseResponseReasoning
     */
    summary?: CreateResponseResponseReasoningSummaryEnum | null;
}


/**
 * @export
 */
export const CreateResponseResponseReasoningEffortEnum = {
    None: 'none',
    Minimal: 'minimal',
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Xhigh: 'xhigh'
} as const;
export type CreateResponseResponseReasoningEffortEnum = typeof CreateResponseResponseReasoningEffortEnum[keyof typeof CreateResponseResponseReasoningEffortEnum];

/**
 * @export
 */
export const CreateResponseResponseReasoningSummaryEnum = {
    Auto: 'auto',
    Concise: 'concise',
    Detailed: 'detailed'
} as const;
export type CreateResponseResponseReasoningSummaryEnum = typeof CreateResponseResponseReasoningSummaryEnum[keyof typeof CreateResponseResponseReasoningSummaryEnum];


/**
 * Check if a given object implements the CreateResponseResponseReasoning interface.
 */
export function instanceOfCreateResponseResponseReasoning(value: object): value is CreateResponseResponseReasoning {
    return true;
}

export function CreateResponseResponseReasoningFromJSON(json: any): CreateResponseResponseReasoning {
    return CreateResponseResponseReasoningFromJSONTyped(json, false);
}

export function CreateResponseResponseReasoningFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponseResponseReasoning {
    if (json == null) {
        return json;
    }
    return {
        
        'effort': json['effort'] == null ? undefined : json['effort'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function CreateResponseResponseReasoningToJSON(json: any): CreateResponseResponseReasoning {
    return CreateResponseResponseReasoningToJSONTyped(json, false);
}

export function CreateResponseResponseReasoningToJSONTyped(value?: CreateResponseResponseReasoning | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'effort': value['effort'],
        'summary': value['summary'],
    };
}

