/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionRequestToolChoiceAnyOf } from './CreateChatCompletionRequestToolChoiceAnyOf';
import {
    CreateChatCompletionRequestToolChoiceAnyOfFromJSON,
    CreateChatCompletionRequestToolChoiceAnyOfFromJSONTyped,
    CreateChatCompletionRequestToolChoiceAnyOfToJSON,
    CreateChatCompletionRequestToolChoiceAnyOfToJSONTyped,
} from './CreateChatCompletionRequestToolChoiceAnyOf';
import type { CreateChatCompletionRequestToolChoiceAnyOfFunction } from './CreateChatCompletionRequestToolChoiceAnyOfFunction';
import {
    CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSON,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSONTyped,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSON,
    CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSONTyped,
} from './CreateChatCompletionRequestToolChoiceAnyOfFunction';

/**
 * Controls which tool is called. "none", "auto", "required", or a specific tool object.
 * @export
 * @interface CreateChatCompletionRequestToolChoice
 */
export interface CreateChatCompletionRequestToolChoice {
    /**
     * 
     * @type {CreateChatCompletionRequestToolChoiceTypeEnum}
     * @memberof CreateChatCompletionRequestToolChoice
     */
    type: CreateChatCompletionRequestToolChoiceTypeEnum;
    /**
     * 
     * @type {CreateChatCompletionRequestToolChoiceAnyOfFunction}
     * @memberof CreateChatCompletionRequestToolChoice
     */
    _function: CreateChatCompletionRequestToolChoiceAnyOfFunction;
}


/**
 * @export
 */
export const CreateChatCompletionRequestToolChoiceTypeEnum = {
    Function: 'function'
} as const;
export type CreateChatCompletionRequestToolChoiceTypeEnum = typeof CreateChatCompletionRequestToolChoiceTypeEnum[keyof typeof CreateChatCompletionRequestToolChoiceTypeEnum];


/**
 * Check if a given object implements the CreateChatCompletionRequestToolChoice interface.
 */
export function instanceOfCreateChatCompletionRequestToolChoice(value: object): value is CreateChatCompletionRequestToolChoice {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestToolChoiceFromJSON(json: any): CreateChatCompletionRequestToolChoice {
    return CreateChatCompletionRequestToolChoiceFromJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestToolChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': CreateChatCompletionRequestToolChoiceAnyOfFunctionFromJSON(json['function']),
    };
}

export function CreateChatCompletionRequestToolChoiceToJSON(json: any): CreateChatCompletionRequestToolChoice {
    return CreateChatCompletionRequestToolChoiceToJSONTyped(json, false);
}

export function CreateChatCompletionRequestToolChoiceToJSONTyped(value?: CreateChatCompletionRequestToolChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': CreateChatCompletionRequestToolChoiceAnyOfFunctionToJSON(value['_function']),
    };
}

