/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The prompt(s) to generate completions for.
 * @export
 * @interface CreateCompletionRequestPrompt
 */
export interface CreateCompletionRequestPrompt {
}

/**
 * Check if a given object implements the CreateCompletionRequestPrompt interface.
 */
export function instanceOfCreateCompletionRequestPrompt(value: object): value is CreateCompletionRequestPrompt {
    return true;
}

export function CreateCompletionRequestPromptFromJSON(json: any): CreateCompletionRequestPrompt {
    return CreateCompletionRequestPromptFromJSONTyped(json, false);
}

export function CreateCompletionRequestPromptFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompletionRequestPrompt {
    return json;
}

export function CreateCompletionRequestPromptToJSON(json: any): CreateCompletionRequestPrompt {
    return CreateCompletionRequestPromptToJSONTyped(json, false);
}

export function CreateCompletionRequestPromptToJSONTyped(value?: CreateCompletionRequestPrompt | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

