/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileObject } from './FileObject';
import {
    FileObjectFromJSON,
    FileObjectFromJSONTyped,
    FileObjectToJSON,
    FileObjectToJSONTyped,
} from './FileObject';

/**
 * 
 * @export
 * @interface FileList
 */
export interface FileList {
    /**
     * 
     * @type {FileListObjectEnum}
     * @memberof FileList
     */
    object: FileListObjectEnum;
    /**
     * 
     * @type {Array<FileObject>}
     * @memberof FileList
     */
    data: Array<FileObject>;
    /**
     * 
     * @type {boolean}
     * @memberof FileList
     */
    has_more: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileList
     */
    first_id: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileList
     */
    last_id: string | null;
}


/**
 * @export
 */
export const FileListObjectEnum = {
    List: 'list'
} as const;
export type FileListObjectEnum = typeof FileListObjectEnum[keyof typeof FileListObjectEnum];


/**
 * Check if a given object implements the FileList interface.
 */
export function instanceOfFileList(value: object): value is FileList {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    if (!('first_id' in value) || value['first_id'] === undefined) return false;
    if (!('last_id' in value) || value['last_id'] === undefined) return false;
    return true;
}

export function FileListFromJSON(json: any): FileList {
    return FileListFromJSONTyped(json, false);
}

export function FileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileList {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(FileObjectFromJSON)),
        'has_more': json['has_more'],
        'first_id': json['first_id'],
        'last_id': json['last_id'],
    };
}

export function FileListToJSON(json: any): FileList {
    return FileListToJSONTyped(json, false);
}

export function FileListToJSONTyped(value?: FileList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(FileObjectToJSON)),
        'has_more': value['has_more'],
        'first_id': value['first_id'],
        'last_id': value['last_id'],
    };
}

