/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileObject
 */
export interface FileObject {
    /**
     * Stable file id with `file-` prefix
     * @type {string}
     * @memberof FileObject
     */
    id: string;
    /**
     * 
     * @type {FileObjectObjectEnum}
     * @memberof FileObject
     */
    object: FileObjectObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof FileObject
     */
    bytes: number;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof FileObject
     */
    created_at: number;
    /**
     * Unix timestamp; defaults to 30 days from upload
     * @type {number}
     * @memberof FileObject
     */
    expires_at: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileObject
     */
    filename: string | null;
    /**
     * 
     * @type {FileObjectPurposeEnum}
     * @memberof FileObject
     */
    purpose: FileObjectPurposeEnum;
}


/**
 * @export
 */
export const FileObjectObjectEnum = {
    File: 'file'
} as const;
export type FileObjectObjectEnum = typeof FileObjectObjectEnum[keyof typeof FileObjectObjectEnum];

/**
 * @export
 */
export const FileObjectPurposeEnum = {
    Vision: 'vision',
    Video: 'video',
    Audio: 'audio',
    Document: 'document'
} as const;
export type FileObjectPurposeEnum = typeof FileObjectPurposeEnum[keyof typeof FileObjectPurposeEnum];


/**
 * Check if a given object implements the FileObject interface.
 */
export function instanceOfFileObject(value: object): value is FileObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    return true;
}

export function FileObjectFromJSON(json: any): FileObject {
    return FileObjectFromJSONTyped(json, false);
}

export function FileObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'bytes': json['bytes'],
        'created_at': json['created_at'],
        'expires_at': json['expires_at'],
        'filename': json['filename'],
        'purpose': json['purpose'],
    };
}

export function FileObjectToJSON(json: any): FileObject {
    return FileObjectToJSONTyped(json, false);
}

export function FileObjectToJSONTyped(value?: FileObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'bytes': value['bytes'],
        'created_at': value['created_at'],
        'expires_at': value['expires_at'],
        'filename': value['filename'],
        'purpose': value['purpose'],
    };
}

