/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDeleted
 */
export interface FileDeleted {
    /**
     * 
     * @type {string}
     * @memberof FileDeleted
     */
    id: string;
    /**
     * 
     * @type {FileDeletedObjectEnum}
     * @memberof FileDeleted
     */
    object: FileDeletedObjectEnum;
    /**
     * Always true on a successful delete
     * @type {boolean}
     * @memberof FileDeleted
     */
    deleted: boolean;
}


/**
 * @export
 */
export const FileDeletedObjectEnum = {
    File: 'file'
} as const;
export type FileDeletedObjectEnum = typeof FileDeletedObjectEnum[keyof typeof FileDeletedObjectEnum];


/**
 * Check if a given object implements the FileDeleted interface.
 */
export function instanceOfFileDeleted(value: object): value is FileDeleted {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function FileDeletedFromJSON(json: any): FileDeleted {
    return FileDeletedFromJSONTyped(json, false);
}

export function FileDeletedFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDeleted {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'deleted': json['deleted'],
    };
}

export function FileDeletedToJSON(json: any): FileDeleted {
    return FileDeletedToJSONTyped(json, false);
}

export function FileDeletedToJSONTyped(value?: FileDeleted | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'deleted': value['deleted'],
    };
}

