/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListModels200ResponseDataInner } from './ListModels200ResponseDataInner';
import {
    ListModels200ResponseDataInnerFromJSON,
    ListModels200ResponseDataInnerFromJSONTyped,
    ListModels200ResponseDataInnerToJSON,
    ListModels200ResponseDataInnerToJSONTyped,
} from './ListModels200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListModels200Response
 */
export interface ListModels200Response {
    /**
     * 
     * @type {ListModels200ResponseObjectEnum}
     * @memberof ListModels200Response
     */
    object: ListModels200ResponseObjectEnum;
    /**
     * 
     * @type {Array<ListModels200ResponseDataInner>}
     * @memberof ListModels200Response
     */
    data: Array<ListModels200ResponseDataInner>;
}


/**
 * @export
 */
export const ListModels200ResponseObjectEnum = {
    List: 'list'
} as const;
export type ListModels200ResponseObjectEnum = typeof ListModels200ResponseObjectEnum[keyof typeof ListModels200ResponseObjectEnum];


/**
 * Check if a given object implements the ListModels200Response interface.
 */
export function instanceOfListModels200Response(value: object): value is ListModels200Response {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListModels200ResponseFromJSON(json: any): ListModels200Response {
    return ListModels200ResponseFromJSONTyped(json, false);
}

export function ListModels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModels200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'data': ((json['data'] as Array<any>).map(ListModels200ResponseDataInnerFromJSON)),
    };
}

export function ListModels200ResponseToJSON(json: any): ListModels200Response {
    return ListModels200ResponseToJSONTyped(json, false);
}

export function ListModels200ResponseToJSONTyped(value?: ListModels200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(ListModels200ResponseDataInnerToJSON)),
    };
}

