/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListModels200ResponseDataInner
 */
export interface ListModels200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    name: string;
    /**
     * 
     * @type {ListModels200ResponseDataInnerObjectEnum}
     * @memberof ListModels200ResponseDataInner
     */
    object: ListModels200ResponseDataInnerObjectEnum;
    /**
     * 
     * @type {number}
     * @memberof ListModels200ResponseDataInner
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    owned_by: string;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    provider: string;
    /**
     * 
     * @type {number}
     * @memberof ListModels200ResponseDataInner
     */
    context_window: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListModels200ResponseDataInner
     */
    capabilities: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    input_per_1m: string;
    /**
     * 
     * @type {string}
     * @memberof ListModels200ResponseDataInner
     */
    output_per_1m: string;
}


/**
 * @export
 */
export const ListModels200ResponseDataInnerObjectEnum = {
    Model: 'model'
} as const;
export type ListModels200ResponseDataInnerObjectEnum = typeof ListModels200ResponseDataInnerObjectEnum[keyof typeof ListModels200ResponseDataInnerObjectEnum];


/**
 * Check if a given object implements the ListModels200ResponseDataInner interface.
 */
export function instanceOfListModels200ResponseDataInner(value: object): value is ListModels200ResponseDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('owned_by' in value) || value['owned_by'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('context_window' in value) || value['context_window'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('input_per_1m' in value) || value['input_per_1m'] === undefined) return false;
    if (!('output_per_1m' in value) || value['output_per_1m'] === undefined) return false;
    return true;
}

export function ListModels200ResponseDataInnerFromJSON(json: any): ListModels200ResponseDataInner {
    return ListModels200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListModels200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModels200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'object': json['object'],
        'created': json['created'],
        'owned_by': json['owned_by'],
        'provider': json['provider'],
        'context_window': json['context_window'],
        'capabilities': json['capabilities'],
        'description': json['description'],
        'input_per_1m': json['input_per_1m'],
        'output_per_1m': json['output_per_1m'],
    };
}

export function ListModels200ResponseDataInnerToJSON(json: any): ListModels200ResponseDataInner {
    return ListModels200ResponseDataInnerToJSONTyped(json, false);
}

export function ListModels200ResponseDataInnerToJSONTyped(value?: ListModels200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'object': value['object'],
        'created': value['created'],
        'owned_by': value['owned_by'],
        'provider': value['provider'],
        'context_window': value['context_window'],
        'capabilities': value['capabilities'],
        'description': value['description'],
        'input_per_1m': value['input_per_1m'],
        'output_per_1m': value['output_per_1m'],
    };
}

