/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOf1
 */
export interface ResponseInputAnyOfInnerAnyOf1 {
    [key: string]: any | any;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOf1TypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOf1
     */
    type: ResponseInputAnyOfInnerAnyOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOf1
     */
    call_id: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOf1
     */
    output: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOf1TypeEnum = {
    FunctionCallOutput: 'function_call_output'
} as const;
export type ResponseInputAnyOfInnerAnyOf1TypeEnum = typeof ResponseInputAnyOfInnerAnyOf1TypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOf1TypeEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOf1 interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOf1(value: object): value is ResponseInputAnyOfInnerAnyOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('call_id' in value) || value['call_id'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOf1FromJSON(json: any): ResponseInputAnyOfInnerAnyOf1 {
    return ResponseInputAnyOfInnerAnyOf1FromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'call_id': json['call_id'],
        'output': json['output'],
    };
}

export function ResponseInputAnyOfInnerAnyOf1ToJSON(json: any): ResponseInputAnyOfInnerAnyOf1 {
    return ResponseInputAnyOfInnerAnyOf1ToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOf1ToJSONTyped(value?: ResponseInputAnyOfInnerAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'call_id': value['call_id'],
        'output': value['output'],
    };
}

