/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseInputAnyOfInnerAnyOfContent } from './ResponseInputAnyOfInnerAnyOfContent';
import {
    ResponseInputAnyOfInnerAnyOfContentFromJSON,
    ResponseInputAnyOfInnerAnyOfContentFromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentToJSON,
    ResponseInputAnyOfInnerAnyOfContentToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContent';

/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOf
 */
export interface ResponseInputAnyOfInnerAnyOf {
    [key: string]: any | any;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfRoleEnum}
     * @memberof ResponseInputAnyOfInnerAnyOf
     */
    role: ResponseInputAnyOfInnerAnyOfRoleEnum;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContent}
     * @memberof ResponseInputAnyOfInnerAnyOf
     */
    content: ResponseInputAnyOfInnerAnyOfContent;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    Developer: 'developer',
    System: 'system'
} as const;
export type ResponseInputAnyOfInnerAnyOfRoleEnum = typeof ResponseInputAnyOfInnerAnyOfRoleEnum[keyof typeof ResponseInputAnyOfInnerAnyOfRoleEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOf interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOf(value: object): value is ResponseInputAnyOfInnerAnyOf {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOfFromJSON(json: any): ResponseInputAnyOfInnerAnyOf {
    return ResponseInputAnyOfInnerAnyOfFromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'role': json['role'],
        'content': ResponseInputAnyOfInnerAnyOfContentFromJSON(json['content']),
    };
}

export function ResponseInputAnyOfInnerAnyOfToJSON(json: any): ResponseInputAnyOfInnerAnyOf {
    return ResponseInputAnyOfInnerAnyOfToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfToJSONTyped(value?: ResponseInputAnyOfInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'role': value['role'],
        'content': ResponseInputAnyOfInnerAnyOfContentToJSON(value['content']),
    };
}

