/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseInputAnyOfInner } from './ResponseInputAnyOfInner';
import {
    ResponseInputAnyOfInnerFromJSON,
    ResponseInputAnyOfInnerFromJSONTyped,
    ResponseInputAnyOfInnerToJSON,
    ResponseInputAnyOfInnerToJSONTyped,
} from './ResponseInputAnyOfInner';

/**
 * Text, image, or file inputs to the model. Can be a string (treated as user message) or an array of input items.
 * @export
 * @interface ResponseInput
 */
export interface ResponseInput {
}

/**
 * Check if a given object implements the ResponseInput interface.
 */
export function instanceOfResponseInput(value: object): value is ResponseInput {
    return true;
}

export function ResponseInputFromJSON(json: any): ResponseInput {
    return ResponseInputFromJSONTyped(json, false);
}

export function ResponseInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInput {
    return json;
}

export function ResponseInputToJSON(json: any): ResponseInput {
    return ResponseInputToJSONTyped(json, false);
}

export function ResponseInputToJSONTyped(value?: ResponseInput | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

