/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2
 */
export interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 {
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2
     */
    type: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2
     */
    file_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2
     */
    file_data?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2
     */
    filename?: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum = {
    InputFile: 'input_file'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2TypeEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2(value: object): value is ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2FromJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2FromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'file_id': json['file_id'] == null ? undefined : json['file_id'],
        'file_data': json['file_data'] == null ? undefined : json['file_data'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2ToJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2ToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2ToJSONTyped(value?: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'file_id': value['file_id'],
        'file_data': value['file_data'],
        'filename': value['filename'],
    };
}

