/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOf2
 */
export interface ResponseInputAnyOfInnerAnyOf2 {
    [key: string]: any | any;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOf2TypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOf2
     */
    type: ResponseInputAnyOfInnerAnyOf2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOf2
     */
    id: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOf2TypeEnum = {
    ItemReference: 'item_reference'
} as const;
export type ResponseInputAnyOfInnerAnyOf2TypeEnum = typeof ResponseInputAnyOfInnerAnyOf2TypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOf2TypeEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOf2 interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOf2(value: object): value is ResponseInputAnyOfInnerAnyOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOf2FromJSON(json: any): ResponseInputAnyOfInnerAnyOf2 {
    return ResponseInputAnyOfInnerAnyOf2FromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOf2 {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'id': json['id'],
    };
}

export function ResponseInputAnyOfInnerAnyOf2ToJSON(json: any): ResponseInputAnyOfInnerAnyOf2 {
    return ResponseInputAnyOfInnerAnyOf2ToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOf2ToJSONTyped(value?: ResponseInputAnyOfInnerAnyOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'id': value['id'],
    };
}

