/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf
 */
export interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf {
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf
     */
    type: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf
     */
    text: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum = {
    InputText: 'input_text'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfTypeEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf(value: object): value is ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfFromJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfFromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
    };
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfToJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfToJSONTyped(value?: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
    };
}

