/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseInputAnyOfInnerAnyOf } from './ResponseInputAnyOfInnerAnyOf';
import {
    ResponseInputAnyOfInnerAnyOfFromJSON,
    ResponseInputAnyOfInnerAnyOfFromJSONTyped,
    ResponseInputAnyOfInnerAnyOfToJSON,
    ResponseInputAnyOfInnerAnyOfToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOf';
import type { ResponseInputAnyOfInnerAnyOfContent } from './ResponseInputAnyOfInnerAnyOfContent';
import {
    ResponseInputAnyOfInnerAnyOfContentFromJSON,
    ResponseInputAnyOfInnerAnyOfContentFromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentToJSON,
    ResponseInputAnyOfInnerAnyOfContentToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContent';
import type { ResponseInputAnyOfInnerAnyOf1 } from './ResponseInputAnyOfInnerAnyOf1';
import {
    ResponseInputAnyOfInnerAnyOf1FromJSON,
    ResponseInputAnyOfInnerAnyOf1FromJSONTyped,
    ResponseInputAnyOfInnerAnyOf1ToJSON,
    ResponseInputAnyOfInnerAnyOf1ToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOf1';
import type { ResponseInputAnyOfInnerAnyOf2 } from './ResponseInputAnyOfInnerAnyOf2';
import {
    ResponseInputAnyOfInnerAnyOf2FromJSON,
    ResponseInputAnyOfInnerAnyOf2FromJSONTyped,
    ResponseInputAnyOfInnerAnyOf2ToJSON,
    ResponseInputAnyOfInnerAnyOf2ToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOf2';

/**
 * 
 * @export
 * @interface ResponseInputAnyOfInner
 */
export interface ResponseInputAnyOfInner {
    /**
     * 
     * @type {ResponseInputAnyOfInnerRoleEnum}
     * @memberof ResponseInputAnyOfInner
     */
    role: ResponseInputAnyOfInnerRoleEnum;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContent}
     * @memberof ResponseInputAnyOfInner
     */
    content: ResponseInputAnyOfInnerAnyOfContent;
    /**
     * 
     * @type {ResponseInputAnyOfInnerTypeEnum}
     * @memberof ResponseInputAnyOfInner
     */
    type: ResponseInputAnyOfInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInner
     */
    call_id: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInner
     */
    output: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInner
     */
    id: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    Developer: 'developer',
    System: 'system'
} as const;
export type ResponseInputAnyOfInnerRoleEnum = typeof ResponseInputAnyOfInnerRoleEnum[keyof typeof ResponseInputAnyOfInnerRoleEnum];

/**
 * @export
 */
export const ResponseInputAnyOfInnerTypeEnum = {
    FunctionCallOutput: 'function_call_output',
    ItemReference: 'item_reference'
} as const;
export type ResponseInputAnyOfInnerTypeEnum = typeof ResponseInputAnyOfInnerTypeEnum[keyof typeof ResponseInputAnyOfInnerTypeEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInner interface.
 */
export function instanceOfResponseInputAnyOfInner(value: object): value is ResponseInputAnyOfInner {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('call_id' in value) || value['call_id'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerFromJSON(json: any): ResponseInputAnyOfInner {
    return ResponseInputAnyOfInnerFromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': ResponseInputAnyOfInnerAnyOfContentFromJSON(json['content']),
        'type': json['type'],
        'call_id': json['call_id'],
        'output': json['output'],
        'id': json['id'],
    };
}

export function ResponseInputAnyOfInnerToJSON(json: any): ResponseInputAnyOfInner {
    return ResponseInputAnyOfInnerToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerToJSONTyped(value?: ResponseInputAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': ResponseInputAnyOfInnerAnyOfContentToJSON(value['content']),
        'type': value['type'],
        'call_id': value['call_id'],
        'output': value['output'],
        'id': value['id'],
    };
}

