/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseUsageInputTokensDetails } from './ResponseUsageInputTokensDetails';
import {
    ResponseUsageInputTokensDetailsFromJSON,
    ResponseUsageInputTokensDetailsFromJSONTyped,
    ResponseUsageInputTokensDetailsToJSON,
    ResponseUsageInputTokensDetailsToJSONTyped,
} from './ResponseUsageInputTokensDetails';
import type { ResponseUsageOutputTokensDetails } from './ResponseUsageOutputTokensDetails';
import {
    ResponseUsageOutputTokensDetailsFromJSON,
    ResponseUsageOutputTokensDetailsFromJSONTyped,
    ResponseUsageOutputTokensDetailsToJSON,
    ResponseUsageOutputTokensDetailsToJSONTyped,
} from './ResponseUsageOutputTokensDetails';

/**
 * 
 * @export
 * @interface ResponseUsage
 */
export interface ResponseUsage {
    /**
     * 
     * @type {number}
     * @memberof ResponseUsage
     */
    input_tokens: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseUsage
     */
    output_tokens: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseUsage
     */
    total_tokens: number;
    /**
     * 
     * @type {ResponseUsageInputTokensDetails}
     * @memberof ResponseUsage
     */
    input_tokens_details?: ResponseUsageInputTokensDetails;
    /**
     * 
     * @type {ResponseUsageOutputTokensDetails}
     * @memberof ResponseUsage
     */
    output_tokens_details?: ResponseUsageOutputTokensDetails;
}

/**
 * Check if a given object implements the ResponseUsage interface.
 */
export function instanceOfResponseUsage(value: object): value is ResponseUsage {
    if (!('input_tokens' in value) || value['input_tokens'] === undefined) return false;
    if (!('output_tokens' in value) || value['output_tokens'] === undefined) return false;
    if (!('total_tokens' in value) || value['total_tokens'] === undefined) return false;
    return true;
}

export function ResponseUsageFromJSON(json: any): ResponseUsage {
    return ResponseUsageFromJSONTyped(json, false);
}

export function ResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'input_tokens': json['input_tokens'],
        'output_tokens': json['output_tokens'],
        'total_tokens': json['total_tokens'],
        'input_tokens_details': json['input_tokens_details'] == null ? undefined : ResponseUsageInputTokensDetailsFromJSON(json['input_tokens_details']),
        'output_tokens_details': json['output_tokens_details'] == null ? undefined : ResponseUsageOutputTokensDetailsFromJSON(json['output_tokens_details']),
    };
}

export function ResponseUsageToJSON(json: any): ResponseUsage {
    return ResponseUsageToJSONTyped(json, false);
}

export function ResponseUsageToJSONTyped(value?: ResponseUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_tokens': value['input_tokens'],
        'output_tokens': value['output_tokens'],
        'total_tokens': value['total_tokens'],
        'input_tokens_details': ResponseUsageInputTokensDetailsToJSON(value['input_tokens_details']),
        'output_tokens_details': ResponseUsageOutputTokensDetailsToJSON(value['output_tokens_details']),
    };
}

