/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseUsageInputTokensDetails
 */
export interface ResponseUsageInputTokensDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof ResponseUsageInputTokensDetails
     */
    cached_tokens: number;
}

/**
 * Check if a given object implements the ResponseUsageInputTokensDetails interface.
 */
export function instanceOfResponseUsageInputTokensDetails(value: object): value is ResponseUsageInputTokensDetails {
    if (!('cached_tokens' in value) || value['cached_tokens'] === undefined) return false;
    return true;
}

export function ResponseUsageInputTokensDetailsFromJSON(json: any): ResponseUsageInputTokensDetails {
    return ResponseUsageInputTokensDetailsFromJSONTyped(json, false);
}

export function ResponseUsageInputTokensDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUsageInputTokensDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'cached_tokens': json['cached_tokens'],
    };
}

export function ResponseUsageInputTokensDetailsToJSON(json: any): ResponseUsageInputTokensDetails {
    return ResponseUsageInputTokensDetailsToJSONTyped(json, false);
}

export function ResponseUsageInputTokensDetailsToJSONTyped(value?: ResponseUsageInputTokensDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'cached_tokens': value['cached_tokens'],
    };
}

