/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseUsageOutputTokensDetails
 */
export interface ResponseUsageOutputTokensDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof ResponseUsageOutputTokensDetails
     */
    reasoning_tokens: number;
}

/**
 * Check if a given object implements the ResponseUsageOutputTokensDetails interface.
 */
export function instanceOfResponseUsageOutputTokensDetails(value: object): value is ResponseUsageOutputTokensDetails {
    if (!('reasoning_tokens' in value) || value['reasoning_tokens'] === undefined) return false;
    return true;
}

export function ResponseUsageOutputTokensDetailsFromJSON(json: any): ResponseUsageOutputTokensDetails {
    return ResponseUsageOutputTokensDetailsFromJSONTyped(json, false);
}

export function ResponseUsageOutputTokensDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUsageOutputTokensDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'reasoning_tokens': json['reasoning_tokens'],
    };
}

export function ResponseUsageOutputTokensDetailsToJSON(json: any): ResponseUsageOutputTokensDetails {
    return ResponseUsageOutputTokensDetailsToJSONTyped(json, false);
}

export function ResponseUsageOutputTokensDetailsToJSONTyped(value?: ResponseUsageOutputTokensDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'reasoning_tokens': value['reasoning_tokens'],
    };
}

