/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1
 */
export interface ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 {
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1
     */
    type: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1
     */
    image_url?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1
     */
    file_id?: string;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1
     */
    detail?: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum = {
    InputImage: 'input_image'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1TypeEnum];

/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum = {
    Auto: 'auto',
    Low: 'low',
    High: 'high'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1DetailEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1(value: object): value is ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1FromJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1FromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'image_url': json['image_url'] == null ? undefined : json['image_url'],
        'file_id': json['file_id'] == null ? undefined : json['file_id'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1ToJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1ToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1ToJSONTyped(value?: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'image_url': value['image_url'],
        'file_id': value['file_id'],
        'detail': value['detail'],
    };
}

