/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf } from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf';
import {
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfFromJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfFromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfToJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOfToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf';
import type { ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1 } from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1';
import {
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1FromJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1FromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1ToJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1ToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf1';
import type { ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2 } from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2';
import {
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2FromJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2FromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2ToJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2ToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContentAnyOfInnerAnyOf2';

/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOfContentAnyOfInner
 */
export interface ResponseInputAnyOfInnerAnyOfContentAnyOfInner {
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    type: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    image_url?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    file_id?: string;
    /**
     * 
     * @type {ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    detail?: ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    file_data?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseInputAnyOfInnerAnyOfContentAnyOfInner
     */
    filename?: string;
}


/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum = {
    InputText: 'input_text',
    InputImage: 'input_image',
    InputFile: 'input_file'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerTypeEnum];

/**
 * @export
 */
export const ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum = {
    Auto: 'auto',
    Low: 'low',
    High: 'high'
} as const;
export type ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum = typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum[keyof typeof ResponseInputAnyOfInnerAnyOfContentAnyOfInnerDetailEnum];


/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOfContentAnyOfInner interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOfContentAnyOfInner(value: object): value is ResponseInputAnyOfInnerAnyOfContentAnyOfInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerFromJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInner {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerFromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOfContentAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'image_url': json['image_url'] == null ? undefined : json['image_url'],
        'file_id': json['file_id'] == null ? undefined : json['file_id'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'file_data': json['file_data'] == null ? undefined : json['file_data'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerToJSON(json: any): ResponseInputAnyOfInnerAnyOfContentAnyOfInner {
    return ResponseInputAnyOfInnerAnyOfContentAnyOfInnerToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentAnyOfInnerToJSONTyped(value?: ResponseInputAnyOfInnerAnyOfContentAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'image_url': value['image_url'],
        'file_id': value['file_id'],
        'detail': value['detail'],
        'file_data': value['file_data'],
        'filename': value['filename'],
    };
}

