/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseInputAnyOfInnerAnyOfContentAnyOfInner } from './ResponseInputAnyOfInnerAnyOfContentAnyOfInner';
import {
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerFromJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerFromJSONTyped,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerToJSON,
    ResponseInputAnyOfInnerAnyOfContentAnyOfInnerToJSONTyped,
} from './ResponseInputAnyOfInnerAnyOfContentAnyOfInner';

/**
 * 
 * @export
 * @interface ResponseInputAnyOfInnerAnyOfContent
 */
export interface ResponseInputAnyOfInnerAnyOfContent {
}

/**
 * Check if a given object implements the ResponseInputAnyOfInnerAnyOfContent interface.
 */
export function instanceOfResponseInputAnyOfInnerAnyOfContent(value: object): value is ResponseInputAnyOfInnerAnyOfContent {
    return true;
}

export function ResponseInputAnyOfInnerAnyOfContentFromJSON(json: any): ResponseInputAnyOfInnerAnyOfContent {
    return ResponseInputAnyOfInnerAnyOfContentFromJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInputAnyOfInnerAnyOfContent {
    return json;
}

export function ResponseInputAnyOfInnerAnyOfContentToJSON(json: any): ResponseInputAnyOfInnerAnyOfContent {
    return ResponseInputAnyOfInnerAnyOfContentToJSONTyped(json, false);
}

export function ResponseInputAnyOfInnerAnyOfContentToJSONTyped(value?: ResponseInputAnyOfInnerAnyOfContent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

