/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileObject } from './FileObject';
import {
    FileObjectFromJSON,
    FileObjectFromJSONTyped,
    FileObjectToJSON,
    FileObjectToJSONTyped,
} from './FileObject';

/**
 * 
 * @export
 * @interface UploadObject
 */
export interface UploadObject {
    /**
     * Stable upload session id with `upload-` prefix
     * @type {string}
     * @memberof UploadObject
     */
    id: string;
    /**
     * 
     * @type {UploadObjectObjectEnum}
     * @memberof UploadObject
     */
    object: UploadObjectObjectEnum;
    /**
     * Declared total size of the file being uploaded
     * @type {number}
     * @memberof UploadObject
     */
    bytes: number;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof UploadObject
     */
    created_at: number;
    /**
     * Unix timestamp (1 hour from creation by default)
     * @type {number}
     * @memberof UploadObject
     */
    expires_at: number;
    /**
     * 
     * @type {string}
     * @memberof UploadObject
     */
    filename: string | null;
    /**
     * 
     * @type {UploadObjectPurposeEnum}
     * @memberof UploadObject
     */
    purpose: UploadObjectPurposeEnum;
    /**
     * 
     * @type {UploadObjectStatusEnum}
     * @memberof UploadObject
     */
    status: UploadObjectStatusEnum;
    /**
     * Populated once status is `completed`
     * @type {FileObject}
     * @memberof UploadObject
     */
    file: FileObject | null;
}


/**
 * @export
 */
export const UploadObjectObjectEnum = {
    Upload: 'upload'
} as const;
export type UploadObjectObjectEnum = typeof UploadObjectObjectEnum[keyof typeof UploadObjectObjectEnum];

/**
 * @export
 */
export const UploadObjectPurposeEnum = {
    Vision: 'vision',
    Video: 'video',
    Audio: 'audio',
    Document: 'document'
} as const;
export type UploadObjectPurposeEnum = typeof UploadObjectPurposeEnum[keyof typeof UploadObjectPurposeEnum];

/**
 * @export
 */
export const UploadObjectStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Cancelled: 'cancelled',
    Expired: 'expired'
} as const;
export type UploadObjectStatusEnum = typeof UploadObjectStatusEnum[keyof typeof UploadObjectStatusEnum];


/**
 * Check if a given object implements the UploadObject interface.
 */
export function instanceOfUploadObject(value: object): value is UploadObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function UploadObjectFromJSON(json: any): UploadObject {
    return UploadObjectFromJSONTyped(json, false);
}

export function UploadObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'bytes': json['bytes'],
        'created_at': json['created_at'],
        'expires_at': json['expires_at'],
        'filename': json['filename'],
        'purpose': json['purpose'],
        'status': json['status'],
        'file': FileObjectFromJSON(json['file']),
    };
}

export function UploadObjectToJSON(json: any): UploadObject {
    return UploadObjectToJSONTyped(json, false);
}

export function UploadObjectToJSONTyped(value?: UploadObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'bytes': value['bytes'],
        'created_at': value['created_at'],
        'expires_at': value['expires_at'],
        'filename': value['filename'],
        'purpose': value['purpose'],
        'status': value['status'],
        'file': FileObjectToJSON(value['file']),
    };
}

