/* tslint:disable */
/* eslint-disable */
/**
 * ai& API
 * Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadPartObject
 */
export interface UploadPartObject {
    /**
     * Stable part id with `part-` prefix
     * @type {string}
     * @memberof UploadPartObject
     */
    id: string;
    /**
     * 
     * @type {UploadPartObjectObjectEnum}
     * @memberof UploadPartObject
     */
    object: UploadPartObjectObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof UploadPartObject
     */
    upload_id: string;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof UploadPartObject
     */
    created_at: number;
}


/**
 * @export
 */
export const UploadPartObjectObjectEnum = {
    UploadPart: 'upload.part'
} as const;
export type UploadPartObjectObjectEnum = typeof UploadPartObjectObjectEnum[keyof typeof UploadPartObjectObjectEnum];


/**
 * Check if a given object implements the UploadPartObject interface.
 */
export function instanceOfUploadPartObject(value: object): value is UploadPartObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('upload_id' in value) || value['upload_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function UploadPartObjectFromJSON(json: any): UploadPartObject {
    return UploadPartObjectFromJSONTyped(json, false);
}

export function UploadPartObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPartObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'upload_id': json['upload_id'],
        'created_at': json['created_at'],
    };
}

export function UploadPartObjectToJSON(json: any): UploadPartObject {
    return UploadPartObjectToJSONTyped(json, false);
}

export function UploadPartObjectToJSONTyped(value?: UploadPartObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'upload_id': value['upload_id'],
        'created_at': value['created_at'],
    };
}

